"""Dados do guia de platina de Wo Long: Fallen Dynasty (jogo base, PT-BR).

57 passos de rota, as 46 batalhas, 75 coletáveis com missão
e local, os 51 troféus, os 17 companheiros, as 5 fases e 10 itens
de preparo.

Este é o ÚNICO arquivo específico do jogo — os demais módulos são genéricos.
"""

# Identificador único do guia (kebab-case): vira o id do plugin e a pasta
# de progresso em %APPDATA%/StreamerSidekick/platinas/<id>/.
GUIDE_ID = "wolong"

GAME_NAME = "Wo Long — Platina"
GAME_SUBTITLE = (
    "Guia PT-BR do jogo base: as 46 batalhas na ordem, 75 coletáveis com local, "
    "as 145 bandeiras e os 51 troféus."
)
ACCENT = "#C8102E"  # vermelho da identidade do jogo

HERO_IMAGE = "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1448440/header.jpg"

# Parágrafo de abertura.
INTRO = "São 51 troféus, nenhum perdível e uma run só — dá para platinar em cerca de 40 horas sem repetir campanha. O que separa isso de uma limpeza infernal no fim é um hábito: em cada uma das 46 batalhas, erguer todas as bandeiras e recolher os itens dali antes de ir ao chefe. Bandeira de Marcação sobe a Fortitude, que é o piso da sua Moral, então quem coleta fica mais forte a cada missão em vez de apanhar."

# Números de destaque exibidos no topo.
HERO_STATS = [
    {
        "value": "51",
        "label": "troféus",
    },
    {
        "value": "46",
        "label": "batalhas",
    },
    {
        "value": "145",
        "label": "bandeiras",
    },
    {
        "value": "75",
        "label": "coletáveis",
    },
    {
        "value": "1 run",
        "label": "sem nada perdível",
    },
]

# As 9 abas do guia.
SECTIONS = [
    {
        "key": "route",
        "num": "01",
        "nav": "Passo a passo",
        "eyebrow": "Rota cronológica",
        "title": "As 46 batalhas na ordem",
        "lead": "Cada batalha já vem com o que recolher nela. Se você seguir a rota, não sobra limpeza no fim.",
        "notices": [
            {
                "tone": "info",
                "text": "Como usar: faça o passo, marque a caixa e siga. As fases podem ser recolhidas clicando no título. ★ marca as batalhas principais.",
            },
            {
                "tone": "red",
                "text": "A regra que decide a run: em toda missão chame um reforço, erga TODAS as bandeiras e recolha os itens listados antes de ir ao chefe. Bandeira de Marcação sobe a Fortitude, que é o piso da sua Moral — quem ignora bandeira apanha no meio do jogo e ainda tem 145 delas para refazer no fim.",
            },
        ],
    },
    {
        "key": "collectibles",
        "num": "02",
        "nav": "Coletáveis",
        "eyebrow": "Well-read · How Precious! · Ascension",
        "title": "75 itens com missão e local",
        "lead": "31 tábuas, 23 Shitieshou e 21 Cascas de Cigarra. Filtre pela missão que você vai jogar e leve a lista do lado.",
        "notices": [
            {
                "tone": "info",
                "text": "Só 20 das 21 Cascas são necessárias para o Ascension — a 21ª é folga. Duas tábuas ficam na própria Vila Oculta, e uma delas só aparece depois de entregar as cascas.",
            },
        ],
    },
    {
        "key": "trophies",
        "num": "03",
        "nav": "51 Troféus",
        "eyebrow": "Platina",
        "title": "Os 51 troféus do jogo base",
        "lead": "1 platina, 2 ouro, 10 prata e 38 bronze. Nenhum é perdível.",
        "notices": [
            {
                "tone": "info",
                "text": "As DLCs (Battle of Zhongyuan, Conqueror of Jiangdong e Upheaval in Jingxiang) têm listas separadas e não contam para esta platina.",
            },
        ],
    },
    {
        "key": "flags",
        "num": "04",
        "nav": "145 Bandeiras",
        "eyebrow": "Fly it High",
        "title": "Bandeiras por batalha",
        "lead": "Marque a batalha quando ela estiver com todas as bandeiras erguidas. São 145 somando as 46 missões.",
        "notices": [
            {
                "tone": "info",
                "text": "A tela de seleção de missão mostra quantas bandeiras você já ergueu em cada batalha — use ela para conferir antes de marcar aqui.",
            },
        ],
    },
    {
        "key": "companions",
        "num": "05",
        "nav": "Companheiros",
        "eyebrow": "Great Gatherings · Side by Side",
        "title": "Os 17 guerreiros e o sistema de Juramento",
        "lead": "Chamar reforço é de graça e resolve três troféus ao mesmo tempo.",
        "notices": [],
    },
    {
        "key": "spells",
        "num": "06",
        "nav": "Feitiços",
        "eyebrow": "Wizardry Master",
        "title": "Os 70 feitiços das Cinco Fases",
        "lead": "14 feitiços por fase. Marque a fase quando tiver comprado os 14 dela.",
        "notices": [
            {
                "tone": "red",
                "text": "Faça a batalha secundária Wizardry Spell Mastery (Parte 3, nível 32). É ela que libera os feitiços de tier alto — sem ela o Wizardry Master é impossível, e muita gente só percebe no fim da run.",
            },
        ],
    },
    {
        "key": "prep",
        "num": "07",
        "nav": "Preparo",
        "eyebrow": "Equipamento e ajustes",
        "title": "O que fazer para não travar depois",
        "lead": "Ajustes de opção, hábitos por missão e os itens de equipamento que viram troféu.",
        "notices": [],
    },
    {
        "key": "visuals",
        "num": "08",
        "nav": "Imagens",
        "eyebrow": "Referência visual",
        "title": "Mecânicas e telas do jogo",
        "lead": "As mecânicas que o guia cita, em imagem. A fonte de cada uma está na legenda.",
        "notices": [],
    },
    {
        "key": "sources",
        "num": "09",
        "nav": "Fontes",
        "eyebrow": "Pesquisa cruzada",
        "title": "Fontes do guia",
        "lead": "A rota foi montada cruzando estes guias.",
        "notices": [],
    },
]

# 01 — Passo a passo: 57 passos.
ROUTE = [
    {
        "phase": "0 — Antes de começar",
        "num": "0.1",
        "title": "Desativar a invasão de jogadores",
        "place": "Opções",
        "when": "Antes da primeira missão",
        "exact": "Nas opções de rede, desative a invasão por outros jogadores.",
        "why": "O troféu Eye for an Eye só conta invasores NPC. Com jogadores reais entrando, a contagem trava e vira grind no fim.",
        "image": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1448440/ss_46d32690392bad490af693cbf3394f8f346890ce.1920x1080.jpg",
    },
    {
        "phase": "0 — Antes de começar",
        "num": "0.2",
        "title": "Entender bandeira, Moral e Fortitude",
        "place": "Tutorial",
        "when": "Antes da primeira missão",
        "exact": "Bandeira de Batalha = checkpoint e sobe a Moral. Bandeira de Marcação = não é checkpoint, sobe a FORTITUDE, que é o piso da sua Moral naquela missão.",
        "why": "É a mecânica que decide toda a run: quanto mais bandeiras você ergue, mais alto seu piso de Moral, e mais fácil fica tudo depois. Ignorar bandeiras é a receita para apanhar no meio do jogo e ainda ter 145 bandeiras de limpeza no fim.",
        "image": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1448440/ss_db17363dfa15e14909f975ff768c666e2fe98f63.1920x1080.jpg",
    },
    {
        "phase": "0 — Antes de começar",
        "num": "0.3",
        "title": "A regra que economiza a run inteira",
        "place": "—",
        "when": "Antes da primeira missão",
        "exact": "Em TODA missão: chame um reforço antes de entrar, erga todas as bandeiras, pegue os coletáveis daquela missão (a rota lista) e só então vá ao chefe.",
        "why": "Seguindo isso, Fly it High, Side by Side, Well-read, How Precious!, Ascension e os Juramentos saem sozinhos junto com a história. É a diferença entre platinar em ~40h e ter que refazer 46 missões no fim.",
        "image": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1448440/ss_616f77c0cf7aa9ad801608d72bbaf188696b7438.1920x1080.jpg",
    },
    {
        "phase": "1 — Encontro",
        "num": "1.1",
        "title": "★ The Village of Calamity",
        "place": "Principal · nível 1",
        "when": "Nível recomendado: 1",
        "exact": "Chame um reforço, erga TODAS as bandeiras (Batalha e Marcação) e recolha: 1 tábua(s). Depois vá ao chefe.",
        "why": "Tutorial. Serve de campo de testes no fim da run para o Great Gatherings.",
        "image": "",
    },
    {
        "phase": "2 — Ilusão",
        "num": "2.1",
        "title": "★ Two Chivalrous Heroes",
        "place": "Principal · nível 5",
        "when": "Nível recomendado: 5",
        "exact": "Chame um reforço, erga TODAS as bandeiras (Batalha e Marcação) e recolha: 1 Casca(s) de Cigarra. Depois vá ao chefe.",
        "why": "Juramento com Zhao Yun ao terminar.",
        "image": "",
    },
    {
        "phase": "2 — Ilusão",
        "num": "2.2",
        "title": "The Yellow Heaven Burns",
        "place": "Sub · nível 10",
        "when": "Nível recomendado: 10",
        "exact": "Chame um reforço, erga TODAS as bandeiras (Batalha e Marcação) e recolha: nenhum coletável fixo. Depois vá ao chefe.",
        "why": "Batalha secundária: conta para Hunting the Great Deer e Battle-hardened, e é level-up barato para a próxima principal.",
        "image": "",
    },
    {
        "phase": "2 — Ilusão",
        "num": "2.3",
        "title": "★ The Valley of Crying Wraiths",
        "place": "Principal · nível 11",
        "when": "Nível recomendado: 11",
        "exact": "Chame um reforço, erga TODAS as bandeiras (Batalha e Marcação) e recolha: 1 Shitieshou; 1 Casca(s) de Cigarra. Depois vá ao chefe.",
        "why": "Juramento com Guan Yu e Zhang Fei. Mate todos os feiticeiros do ritual → Staunching Heresy.",
        "image": "",
    },
    {
        "phase": "2 — Ilusão",
        "num": "2.4",
        "title": "Tale of Guiguzi",
        "place": "Sub · nível 13",
        "when": "Nível recomendado: 13",
        "exact": "Chame um reforço, erga TODAS as bandeiras (Batalha e Marcação) e recolha: nenhum coletável fixo. Depois vá ao chefe.",
        "why": "Batalha secundária: conta para Hunting the Great Deer e Battle-hardened, e é level-up barato para a próxima principal.",
        "image": "",
    },
    {
        "phase": "2 — Ilusão",
        "num": "2.5",
        "title": "★ The Demon Fort of the Yellow Heaven",
        "place": "Principal · nível 17",
        "when": "Nível recomendado: 17",
        "exact": "Chame um reforço, erga TODAS as bandeiras (Batalha e Marcação) e recolha: 1 tábua(s); 1 Shitieshou; 1 Casca(s) de Cigarra. Depois vá ao chefe.",
        "why": "Juramento com Sun Jian.",
        "image": "",
    },
    {
        "phase": "2 — Ilusão",
        "num": "2.6",
        "title": "The Flying Swallow of Heishan",
        "place": "Sub · nível 20",
        "when": "Nível recomendado: 20",
        "exact": "Chame um reforço, erga TODAS as bandeiras (Batalha e Marcação) e recolha: 1 Shitieshou. Depois vá ao chefe.",
        "why": "Batalha secundária: conta para Hunting the Great Deer e Battle-hardened, e é level-up barato para a próxima principal.",
        "image": "",
    },
    {
        "phase": "3 — Corrupção",
        "num": "3.1",
        "title": "★ In Search of the Immortal Wizard",
        "place": "Principal · nível 25",
        "when": "Nível recomendado: 25",
        "exact": "Chame um reforço, erga TODAS as bandeiras (Batalha e Marcação) e recolha: 1 tábua(s); 1 Shitieshou; 1 Casca(s) de Cigarra. Depois vá ao chefe.",
        "why": "Juramento com Zuo Ci.",
        "image": "",
    },
    {
        "phase": "3 — Corrupção",
        "num": "3.2",
        "title": "Shadow of the Sacred Mountain",
        "place": "Sub · nível 27",
        "when": "Nível recomendado: 27",
        "exact": "Chame um reforço, erga TODAS as bandeiras (Batalha e Marcação) e recolha: 1 Shitieshou. Depois vá ao chefe.",
        "why": "Batalha secundária: conta para Hunting the Great Deer e Battle-hardened, e é level-up barato para a próxima principal.",
        "image": "",
    },
    {
        "phase": "3 — Corrupção",
        "num": "3.3",
        "title": "★ Fall of the Corrupted Eunuch",
        "place": "Principal · nível 29",
        "when": "Nível recomendado: 29",
        "exact": "Chame um reforço, erga TODAS as bandeiras (Batalha e Marcação) e recolha: 2 tábua(s); 1 Shitieshou; 2 Casca(s) de Cigarra. Depois vá ao chefe.",
        "why": "Juramento com Cao Cao. Salve os eremitas presos → Dogged Justice.",
        "image": "",
    },
    {
        "phase": "3 — Corrupção",
        "num": "3.4",
        "title": "Wizardry Spell Mastery",
        "place": "Sub · nível 32",
        "when": "Nível recomendado: 32",
        "exact": "Chame um reforço, erga TODAS as bandeiras (Batalha e Marcação) e recolha: nenhum coletável fixo. Depois vá ao chefe.",
        "why": "OBRIGATÓRIA para o Wizardry Master: libera os feitiços de tier alto.",
        "image": "",
    },
    {
        "phase": "3 — Corrupção",
        "num": "3.5",
        "title": "Escape from the Capital",
        "place": "Sub · nível 33",
        "when": "Nível recomendado: 33",
        "exact": "Chame um reforço, erga TODAS as bandeiras (Batalha e Marcação) e recolha: 1 Shitieshou. Depois vá ao chefe.",
        "why": "Batalha secundária: conta para Hunting the Great Deer e Battle-hardened, e é level-up barato para a próxima principal.",
        "image": "",
    },
    {
        "phase": "3 — Corrupção",
        "num": "3.6",
        "title": "The Valorous Trio",
        "place": "Sub · nível 35",
        "when": "Nível recomendado: 35",
        "exact": "Chame um reforço, erga TODAS as bandeiras (Batalha e Marcação) e recolha: nenhum coletável fixo. Depois vá ao chefe.",
        "why": "Batalha secundária: conta para Hunting the Great Deer e Battle-hardened, e é level-up barato para a próxima principal.",
        "image": "",
    },
    {
        "phase": "4 — Tirania",
        "num": "4.1",
        "title": "★ The Battle of Hulaoguan Pass",
        "place": "Principal · nível 37",
        "when": "Nível recomendado: 37",
        "exact": "Chame um reforço, erga TODAS as bandeiras (Batalha e Marcação) e recolha: 2 tábua(s); 1 Shitieshou; 1 Casca(s) de Cigarra. Depois vá ao chefe.",
        "why": "Repila as forças de Lu Bu → Mightiest of Men. Use a balista para matar 5 → Strung Bow.",
        "image": "",
    },
    {
        "phase": "4 — Tirania",
        "num": "4.2",
        "title": "Like Father, Like Son",
        "place": "Sub · nível 41",
        "when": "Nível recomendado: 41",
        "exact": "Chame um reforço, erga TODAS as bandeiras (Batalha e Marcação) e recolha: nenhum coletável fixo. Depois vá ao chefe.",
        "why": "Batalha secundária: conta para Hunting the Great Deer e Battle-hardened, e é level-up barato para a próxima principal.",
        "image": "",
    },
    {
        "phase": "4 — Tirania",
        "num": "4.3",
        "title": "★ Centuries of Glory Burned Away",
        "place": "Principal · nível 43",
        "when": "Nível recomendado: 43",
        "exact": "Chame um reforço, erga TODAS as bandeiras (Batalha e Marcação) e recolha: 3 tábua(s); 1 Shitieshou; 2 Casca(s) de Cigarra. Depois vá ao chefe.",
        "why": "Juramento com Lady Zhen. Repila o Xielong → Heroes will Rise.",
        "image": "",
    },
    {
        "phase": "4 — Tirania",
        "num": "4.4",
        "title": "The Lost Sacred Artifact",
        "place": "Sub · nível 45",
        "when": "Nível recomendado: 45",
        "exact": "Chame um reforço, erga TODAS as bandeiras (Batalha e Marcação) e recolha: 1 Shitieshou. Depois vá ao chefe.",
        "why": "Batalha secundária: conta para Hunting the Great Deer e Battle-hardened, e é level-up barato para a próxima principal.",
        "image": "",
    },
    {
        "phase": "4 — Tirania",
        "num": "4.5",
        "title": "★ Darkness Over the Hanshui River",
        "place": "Principal · nível 49",
        "when": "Nível recomendado: 49",
        "exact": "Chame um reforço, erga TODAS as bandeiras (Batalha e Marcação) e recolha: 2 tábua(s); 1 Shitieshou; 1 Casca(s) de Cigarra. Depois vá ao chefe.",
        "why": "Juramento com Sun Ce e Sun Quan.",
        "image": "",
    },
    {
        "phase": "4 — Tirania",
        "num": "4.6",
        "title": "The Tiger's Loyal Subjects",
        "place": "Sub · nível 53",
        "when": "Nível recomendado: 53",
        "exact": "Chame um reforço, erga TODAS as bandeiras (Batalha e Marcação) e recolha: nenhum coletável fixo. Depois vá ao chefe.",
        "why": "Batalha secundária: conta para Hunting the Great Deer e Battle-hardened, e é level-up barato para a próxima principal.",
        "image": "",
    },
    {
        "phase": "4 — Tirania",
        "num": "4.7",
        "title": "★ Tyrant's Final Banquet",
        "place": "Principal · nível 55",
        "when": "Nível recomendado: 55",
        "exact": "Chame um reforço, erga TODAS as bandeiras (Batalha e Marcação) e recolha: 3 tábua(s); 1 Shitieshou; 2 Casca(s) de Cigarra. Depois vá ao chefe.",
        "why": "Juramento com Hong Jing.",
        "image": "",
    },
    {
        "phase": "4 — Tirania",
        "num": "4.8",
        "title": "Fate of the Entertainer",
        "place": "Sub · nível 57",
        "when": "Nível recomendado: 57",
        "exact": "Chame um reforço, erga TODAS as bandeiras (Batalha e Marcação) e recolha: 2 tábua(s); 1 Shitieshou. Depois vá ao chefe.",
        "why": "Batalha secundária: conta para Hunting the Great Deer e Battle-hardened, e é level-up barato para a próxima principal.",
        "image": "",
    },
    {
        "phase": "4 — Tirania",
        "num": "4.9",
        "title": "Realm of Battle",
        "place": "Sub · nível 57",
        "when": "Nível recomendado: 57",
        "exact": "Chame um reforço, erga TODAS as bandeiras (Batalha e Marcação) e recolha: nenhum coletável fixo. Depois vá ao chefe.",
        "why": "Batalha secundária: conta para Hunting the Great Deer e Battle-hardened, e é level-up barato para a próxima principal.",
        "image": "",
    },
    {
        "phase": "4 — Tirania",
        "num": "4.10",
        "title": "Zhao Yun's Exile",
        "place": "Sub · nível 57",
        "when": "Nível recomendado: 57",
        "exact": "Chame um reforço, erga TODAS as bandeiras (Batalha e Marcação) e recolha: nenhum coletável fixo. Depois vá ao chefe.",
        "why": "Batalha secundária: conta para Hunting the Great Deer e Battle-hardened, e é level-up barato para a próxima principal.",
        "image": "",
    },
    {
        "phase": "4 — Tirania",
        "num": "4.11",
        "title": "Massacre of Meiwu Fort",
        "place": "Sub · nível 58",
        "when": "Nível recomendado: 58",
        "exact": "Chame um reforço, erga TODAS as bandeiras (Batalha e Marcação) e recolha: nenhum coletável fixo. Depois vá ao chefe.",
        "why": "Batalha secundária: conta para Hunting the Great Deer e Battle-hardened, e é level-up barato para a próxima principal.",
        "image": "",
    },
    {
        "phase": "4 — Tirania",
        "num": "4.12",
        "title": "The Unparalleled Spear",
        "place": "Sub · nível 59",
        "when": "Nível recomendado: 59",
        "exact": "Chame um reforço, erga TODAS as bandeiras (Batalha e Marcação) e recolha: nenhum coletável fixo. Depois vá ao chefe.",
        "why": "Batalha secundária: conta para Hunting the Great Deer e Battle-hardened, e é level-up barato para a próxima principal.",
        "image": "",
    },
    {
        "phase": "4 — Tirania",
        "num": "4.13",
        "title": "Green Plum, Warm Liquor",
        "place": "Sub · nível 60",
        "when": "Nível recomendado: 60",
        "exact": "Chame um reforço, erga TODAS as bandeiras (Batalha e Marcação) e recolha: nenhum coletável fixo. Depois vá ao chefe.",
        "why": "Batalha secundária: conta para Hunting the Great Deer e Battle-hardened, e é level-up barato para a próxima principal.",
        "image": "",
    },
    {
        "phase": "5 — Fortitude",
        "num": "5.1",
        "title": "★ War's Flames Blaze Fiercely",
        "place": "Principal · nível 61",
        "when": "Nível recomendado: 61",
        "exact": "Chame um reforço, erga TODAS as bandeiras (Batalha e Marcação) e recolha: 1 Shitieshou; 2 Casca(s) de Cigarra. Depois vá ao chefe.",
        "why": "Juramento com Xiahou Dun e Xiahou Yuan.",
        "image": "",
    },
    {
        "phase": "5 — Fortitude",
        "num": "5.2",
        "title": "The Uninhibited Heart",
        "place": "Sub · nível 62",
        "when": "Nível recomendado: 62",
        "exact": "Chame um reforço, erga TODAS as bandeiras (Batalha e Marcação) e recolha: 1 tábua(s); 1 Shitieshou. Depois vá ao chefe.",
        "why": "Batalha secundária: conta para Hunting the Great Deer e Battle-hardened, e é level-up barato para a próxima principal.",
        "image": "",
    },
    {
        "phase": "5 — Fortitude",
        "num": "5.3",
        "title": "★ The Way of the Warrior",
        "place": "Principal · nível 67",
        "when": "Nível recomendado: 67",
        "exact": "Chame um reforço, erga TODAS as bandeiras (Batalha e Marcação) e recolha: 1 Shitieshou; 1 Casca(s) de Cigarra. Depois vá ao chefe.",
        "why": "Juramento com Zhang Liao.",
        "image": "",
    },
    {
        "phase": "5 — Fortitude",
        "num": "5.4",
        "title": "Caliber of a Hero",
        "place": "Sub · nível 69",
        "when": "Nível recomendado: 69",
        "exact": "Chame um reforço, erga TODAS as bandeiras (Batalha e Marcação) e recolha: nenhum coletável fixo. Depois vá ao chefe.",
        "why": "Batalha secundária: conta para Hunting the Great Deer e Battle-hardened, e é level-up barato para a próxima principal.",
        "image": "",
    },
    {
        "phase": "5 — Fortitude",
        "num": "5.5",
        "title": "Legend of the Thunder God",
        "place": "Sub · nível 71",
        "when": "Nível recomendado: 71",
        "exact": "Chame um reforço, erga TODAS as bandeiras (Batalha e Marcação) e recolha: nenhum coletável fixo. Depois vá ao chefe.",
        "why": "Batalha secundária: conta para Hunting the Great Deer e Battle-hardened, e é level-up barato para a próxima principal.",
        "image": "",
    },
    {
        "phase": "5 — Fortitude",
        "num": "5.6",
        "title": "★ Lu Bu, Mightiest Among Men",
        "place": "Principal · nível 73",
        "when": "Nível recomendado: 73",
        "exact": "Chame um reforço, erga TODAS as bandeiras (Batalha e Marcação) e recolha: 1 Shitieshou; 1 Casca(s) de Cigarra. Depois vá ao chefe.",
        "why": "Juramento com Lu Bu.",
        "image": "",
    },
    {
        "phase": "5 — Fortitude",
        "num": "5.7",
        "title": "The Scarlet Crystal",
        "place": "Sub · nível 76",
        "when": "Nível recomendado: 76",
        "exact": "Chame um reforço, erga TODAS as bandeiras (Batalha e Marcação) e recolha: nenhum coletável fixo. Depois vá ao chefe.",
        "why": "Batalha secundária: conta para Hunting the Great Deer e Battle-hardened, e é level-up barato para a próxima principal.",
        "image": "",
    },
    {
        "phase": "5 — Fortitude",
        "num": "5.8",
        "title": "Preachers of the Dark Path",
        "place": "Sub · nível 77",
        "when": "Nível recomendado: 77",
        "exact": "Chame um reforço, erga TODAS as bandeiras (Batalha e Marcação) e recolha: nenhum coletável fixo. Depois vá ao chefe.",
        "why": "Batalha secundária: conta para Hunting the Great Deer e Battle-hardened, e é level-up barato para a próxima principal.",
        "image": "",
    },
    {
        "phase": "6 — Malícia",
        "num": "6.1",
        "title": "★ Behold the Glaive of Righteousness",
        "place": "Principal · nível 79",
        "when": "Nível recomendado: 79",
        "exact": "Chame um reforço, erga TODAS as bandeiras (Batalha e Marcação) e recolha: 3 tábua(s); 1 Shitieshou; 2 Casca(s) de Cigarra. Depois vá ao chefe.",
        "why": "Juramento com Liu Bei.",
        "image": "",
    },
    {
        "phase": "6 — Malícia",
        "num": "6.2",
        "title": "The Assault on Wuchao",
        "place": "Sub · nível 80",
        "when": "Nível recomendado: 80",
        "exact": "Chame um reforço, erga TODAS as bandeiras (Batalha e Marcação) e recolha: 1 Shitieshou. Depois vá ao chefe.",
        "why": "Batalha secundária: conta para Hunting the Great Deer e Battle-hardened, e é level-up barato para a próxima principal.",
        "image": "",
    },
    {
        "phase": "6 — Malícia",
        "num": "6.3",
        "title": "Let's Make Our Armor Shine!",
        "place": "Sub · nível 83",
        "when": "Nível recomendado: 83",
        "exact": "Chame um reforço, erga TODAS as bandeiras (Batalha e Marcação) e recolha: 1 Shitieshou. Depois vá ao chefe.",
        "why": "Batalha secundária: conta para Hunting the Great Deer e Battle-hardened, e é level-up barato para a próxima principal.",
        "image": "",
    },
    {
        "phase": "6 — Malícia",
        "num": "6.4",
        "title": "The Fearless Blade",
        "place": "Sub · nível 84",
        "when": "Nível recomendado: 84",
        "exact": "Chame um reforço, erga TODAS as bandeiras (Batalha e Marcação) e recolha: nenhum coletável fixo. Depois vá ao chefe.",
        "why": "Batalha secundária: conta para Hunting the Great Deer e Battle-hardened, e é level-up barato para a próxima principal.",
        "image": "",
    },
    {
        "phase": "6 — Malícia",
        "num": "6.5",
        "title": "★ Decisive Battle of Guandu",
        "place": "Principal · nível 85",
        "when": "Nível recomendado: 85",
        "exact": "Chame um reforço, erga TODAS as bandeiras (Batalha e Marcação) e recolha: 3 tábua(s); 1 Shitieshou; 2 Casca(s) de Cigarra. Depois vá ao chefe.",
        "why": "Juramento com Yuan Shao.",
        "image": "",
    },
    {
        "phase": "6 — Malícia",
        "num": "6.6",
        "title": "Heirloom Seal of the Realm",
        "place": "Sub · nível 88",
        "when": "Nível recomendado: 88",
        "exact": "Chame um reforço, erga TODAS as bandeiras (Batalha e Marcação) e recolha: 1 Shitieshou. Depois vá ao chefe.",
        "why": "Batalha secundária: conta para Hunting the Great Deer e Battle-hardened, e é level-up barato para a próxima principal.",
        "image": "",
    },
    {
        "phase": "6 — Malícia",
        "num": "6.7",
        "title": "The Request of Goddess Luo",
        "place": "Sub · nível 90",
        "when": "Nível recomendado: 90",
        "exact": "Chame um reforço, erga TODAS as bandeiras (Batalha e Marcação) e recolha: nenhum coletável fixo. Depois vá ao chefe.",
        "why": "Batalha secundária: conta para Hunting the Great Deer e Battle-hardened, e é level-up barato para a próxima principal.",
        "image": "",
    },
    {
        "phase": "7 — Ascensão",
        "num": "7.1",
        "title": "★ The Crouching Dragon Roars",
        "place": "Principal · nível 93",
        "when": "Nível recomendado: 93",
        "exact": "Chame um reforço, erga TODAS as bandeiras (Batalha e Marcação) e recolha: 5 tábua(s). Depois vá ao chefe.",
        "why": "Missão final: derrota o Yu Ji (Annihilator of Evil) e fecha a história (Open Eyes).",
        "image": "",
    },
    {
        "phase": "7 — Ascensão",
        "num": "7.2",
        "title": "The Two Walls Stand Tall",
        "place": "Sub · nível 97",
        "when": "Nível recomendado: 97",
        "exact": "Chame um reforço, erga TODAS as bandeiras (Batalha e Marcação) e recolha: nenhum coletável fixo. Depois vá ao chefe.",
        "why": "Batalha secundária: conta para Hunting the Great Deer e Battle-hardened, e é level-up barato para a próxima principal.",
        "image": "",
    },
    {
        "phase": "7 — Ascensão",
        "num": "7.3",
        "title": "Let's Make Our Halberds Shine!",
        "place": "Sub · nível 98",
        "when": "Nível recomendado: 98",
        "exact": "Chame um reforço, erga TODAS as bandeiras (Batalha e Marcação) e recolha: 1 Shitieshou. Depois vá ao chefe.",
        "why": "Batalha secundária: conta para Hunting the Great Deer e Battle-hardened, e é level-up barato para a próxima principal.",
        "image": "",
    },
    {
        "phase": "7 — Ascensão",
        "num": "7.4",
        "title": "Pride of the Yuan Clan",
        "place": "Sub · nível 99",
        "when": "Nível recomendado: 99",
        "exact": "Chame um reforço, erga TODAS as bandeiras (Batalha e Marcação) e recolha: nenhum coletável fixo. Depois vá ao chefe.",
        "why": "Batalha secundária: conta para Hunting the Great Deer e Battle-hardened, e é level-up barato para a próxima principal.",
        "image": "",
    },
    {
        "phase": "7 — Ascensão",
        "num": "7.5",
        "title": "The Crouching Dragon's Trial",
        "place": "Sub · nível 100",
        "when": "Nível recomendado: 100",
        "exact": "Chame um reforço, erga TODAS as bandeiras (Batalha e Marcação) e recolha: nenhum coletável fixo. Depois vá ao chefe.",
        "why": "Batalha secundária: conta para Hunting the Great Deer e Battle-hardened, e é level-up barato para a próxima principal.",
        "image": "",
    },
    {
        "phase": "8 — Limpeza final (depois da história)",
        "num": "8.1",
        "title": "Entregar as 20 Cascas de Cigarra ao Eremita",
        "place": "Vila Oculta do Monte Tianzhushan",
        "when": "Depois de coletar 20",
        "exact": "Suba na torre mais alta da Vila Oculta e entregue. FAÇA BACKUP DO SAVE antes da última entrega.",
        "why": "Ascension. Há relatos do troféu não estourar; com backup você recarrega e tenta de novo em vez de refazer coleta.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/ccc33cdd80528faab55cf68d0196325123a6535d.jpg",
    },
    {
        "phase": "8 — Limpeza final (depois da história)",
        "num": "8.2",
        "title": "Entregar as 31 tábuas ao aldeão",
        "place": "Vila Oculta do Monte Tianzhushan",
        "when": "Depois de coletar 31",
        "exact": "Na cabana em frente ao silo de palha, no centro da Vila Oculta. Backup do save antes da última.",
        "why": "Well-read, o troféu mais raro do jogo. Duas das 31 estão na própria vila — e uma delas só aparece DEPOIS de entregar as 20 cascas.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/ecc38616d3ea942720a1a7bdcdee8888d4b38d08.jpg",
    },
    {
        "phase": "8 — Limpeza final (depois da história)",
        "num": "8.3",
        "title": "Aprender os 70 feitiços",
        "place": "Qualquer bandeira",
        "when": "Nível 80+",
        "exact": "Bandeira → Feitiços → Aprender. Compre os 14 de cada uma das 5 fases.",
        "why": "Wizardry Master. Você precisa ter feito a missão Wizardry Spell Mastery (Parte 3) para os tiers altos aparecerem, e Pontos de Feitiço suficientes — o que acontece por volta do nível 80.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/3df3d4b302c94f49a2788deadbee2acfa8c2e7c9.jpg",
    },
    {
        "phase": "8 — Limpeza final (depois da história)",
        "num": "8.4",
        "title": "Chamar os 17 companheiros",
        "place": "The Village of Calamity",
        "when": "Depois da história",
        "exact": "Na bandeira da Vila Oculta, escolha a missão tutorial na dificuldade Dragão Ascendente. Chame um companheiro, comece, saia. Repita com os 17.",
        "why": "Great Gatherings. Não precisa terminar a missão — basta chamar. Depois da história todos ficam disponíveis, então dá para varrer a lista em poucos minutos.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/04bfbb5d8bc19561fa72604c9afcd17339cfec1e.jpg",
    },
    {
        "phase": "8 — Limpeza final (depois da história)",
        "num": "8.5",
        "title": "Subir um Juramento até o nível 10",
        "place": "Qualquer bandeira",
        "when": "Fim",
        "exact": "Leve sempre o mesmo companheiro e/ou use Taças de Cordialidade nele. No nível 10, resgate a bênção numa bandeira.",
        "why": "Merit Beyond Measure. Se você chamou reforço em toda missão como o passo 0.3 manda, alguém já vai estar perto do 10.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/0306f61755667f0aaf78783548b2f676df5fc1e8.jpg",
    },
    {
        "phase": "8 — Limpeza final (depois da história)",
        "num": "8.6",
        "title": "Fechar equipamento e nível",
        "place": "Forja / bandeiras",
        "when": "Fim",
        "exact": "Arma +9, armadura +9, Pote de Cura no máximo, conjunto 4 estrelas completo e nível 80.",
        "why": "Keen-edged, Adamantine, Pots and Potions, Fantastic Form e Only at Eighty. Ver a aba Preparo.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/ae2af9a47c65ba3e5eb10342c2e1ce4b9bbcdc2a.jpg",
    },
    {
        "phase": "8 — Limpeza final (depois da história)",
        "num": "8.7",
        "title": "Conferir bandeiras e coletáveis que faltam",
        "place": "Seleção de missão",
        "when": "Fim",
        "exact": "A tela de seleção de missão mostra o total de bandeiras erguidas por missão. Refaça as que não estiverem completas.",
        "why": "É a rede de segurança do Fly it High. Se você seguiu o passo 0.3, aqui não deve faltar quase nada.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/b24ea78d9642d16bb52d42531e1a35b7eca2ec22.jpg",
    },
    {
        "phase": "8 — Limpeza final (depois da história)",
        "num": "8.8",
        "title": "Platina — Wo Long",
        "place": "—",
        "when": "Fim",
        "exact": "Com os 50 anteriores, a platina cai.",
        "why": "Nada é perdível: qualquer troféu que faltar pode ser refeito à vontade.",
        "image": "",
    },
]

# As 46 batalhas (16 principais + 30 secundárias).
MISSIONS = [
    {
        "part": "1 — Encontro",
        "kind": "principal",
        "name": "The Village of Calamity",
        "level": 1,
        "note": "Tutorial. Serve de campo de testes no fim da run para o Great Gatherings.",
    },
    {
        "part": "2 — Ilusão",
        "kind": "principal",
        "name": "Two Chivalrous Heroes",
        "level": 5,
        "note": "Juramento com Zhao Yun ao terminar.",
    },
    {
        "part": "2 — Ilusão",
        "kind": "sub",
        "name": "The Yellow Heaven Burns",
        "level": 10,
        "note": "",
    },
    {
        "part": "2 — Ilusão",
        "kind": "principal",
        "name": "The Valley of Crying Wraiths",
        "level": 11,
        "note": "Juramento com Guan Yu e Zhang Fei. Mate todos os feiticeiros do ritual → Staunching Heresy.",
    },
    {
        "part": "2 — Ilusão",
        "kind": "sub",
        "name": "Tale of Guiguzi",
        "level": 13,
        "note": "",
    },
    {
        "part": "2 — Ilusão",
        "kind": "principal",
        "name": "The Demon Fort of the Yellow Heaven",
        "level": 17,
        "note": "Juramento com Sun Jian.",
    },
    {
        "part": "2 — Ilusão",
        "kind": "sub",
        "name": "The Flying Swallow of Heishan",
        "level": 20,
        "note": "",
    },
    {
        "part": "3 — Corrupção",
        "kind": "principal",
        "name": "In Search of the Immortal Wizard",
        "level": 25,
        "note": "Juramento com Zuo Ci.",
    },
    {
        "part": "3 — Corrupção",
        "kind": "sub",
        "name": "Shadow of the Sacred Mountain",
        "level": 27,
        "note": "",
    },
    {
        "part": "3 — Corrupção",
        "kind": "principal",
        "name": "Fall of the Corrupted Eunuch",
        "level": 29,
        "note": "Juramento com Cao Cao. Salve os eremitas presos → Dogged Justice.",
    },
    {
        "part": "3 — Corrupção",
        "kind": "sub",
        "name": "Wizardry Spell Mastery",
        "level": 32,
        "note": "OBRIGATÓRIA para o Wizardry Master: libera os feitiços de tier alto.",
    },
    {
        "part": "3 — Corrupção",
        "kind": "sub",
        "name": "Escape from the Capital",
        "level": 33,
        "note": "",
    },
    {
        "part": "3 — Corrupção",
        "kind": "sub",
        "name": "The Valorous Trio",
        "level": 35,
        "note": "",
    },
    {
        "part": "4 — Tirania",
        "kind": "principal",
        "name": "The Battle of Hulaoguan Pass",
        "level": 37,
        "note": "Repila as forças de Lu Bu → Mightiest of Men. Use a balista para matar 5 → Strung Bow.",
    },
    {
        "part": "4 — Tirania",
        "kind": "sub",
        "name": "Like Father, Like Son",
        "level": 41,
        "note": "",
    },
    {
        "part": "4 — Tirania",
        "kind": "principal",
        "name": "Centuries of Glory Burned Away",
        "level": 43,
        "note": "Juramento com Lady Zhen. Repila o Xielong → Heroes will Rise.",
    },
    {
        "part": "4 — Tirania",
        "kind": "sub",
        "name": "The Lost Sacred Artifact",
        "level": 45,
        "note": "",
    },
    {
        "part": "4 — Tirania",
        "kind": "principal",
        "name": "Darkness Over the Hanshui River",
        "level": 49,
        "note": "Juramento com Sun Ce e Sun Quan.",
    },
    {
        "part": "4 — Tirania",
        "kind": "sub",
        "name": "The Tiger's Loyal Subjects",
        "level": 53,
        "note": "",
    },
    {
        "part": "4 — Tirania",
        "kind": "principal",
        "name": "Tyrant's Final Banquet",
        "level": 55,
        "note": "Juramento com Hong Jing.",
    },
    {
        "part": "4 — Tirania",
        "kind": "sub",
        "name": "Fate of the Entertainer",
        "level": 57,
        "note": "",
    },
    {
        "part": "4 — Tirania",
        "kind": "sub",
        "name": "Realm of Battle",
        "level": 57,
        "note": "",
    },
    {
        "part": "4 — Tirania",
        "kind": "sub",
        "name": "Zhao Yun's Exile",
        "level": 57,
        "note": "",
    },
    {
        "part": "4 — Tirania",
        "kind": "sub",
        "name": "Massacre of Meiwu Fort",
        "level": 58,
        "note": "",
    },
    {
        "part": "4 — Tirania",
        "kind": "sub",
        "name": "The Unparalleled Spear",
        "level": 59,
        "note": "",
    },
    {
        "part": "4 — Tirania",
        "kind": "sub",
        "name": "Green Plum, Warm Liquor",
        "level": 60,
        "note": "",
    },
    {
        "part": "5 — Fortitude",
        "kind": "principal",
        "name": "War's Flames Blaze Fiercely",
        "level": 61,
        "note": "Juramento com Xiahou Dun e Xiahou Yuan.",
    },
    {
        "part": "5 — Fortitude",
        "kind": "sub",
        "name": "The Uninhibited Heart",
        "level": 62,
        "note": "",
    },
    {
        "part": "5 — Fortitude",
        "kind": "principal",
        "name": "The Way of the Warrior",
        "level": 67,
        "note": "Juramento com Zhang Liao.",
    },
    {
        "part": "5 — Fortitude",
        "kind": "sub",
        "name": "Caliber of a Hero",
        "level": 69,
        "note": "",
    },
    {
        "part": "5 — Fortitude",
        "kind": "sub",
        "name": "Legend of the Thunder God",
        "level": 71,
        "note": "",
    },
    {
        "part": "5 — Fortitude",
        "kind": "principal",
        "name": "Lu Bu, Mightiest Among Men",
        "level": 73,
        "note": "Juramento com Lu Bu.",
    },
    {
        "part": "5 — Fortitude",
        "kind": "sub",
        "name": "The Scarlet Crystal",
        "level": 76,
        "note": "",
    },
    {
        "part": "5 — Fortitude",
        "kind": "sub",
        "name": "Preachers of the Dark Path",
        "level": 77,
        "note": "",
    },
    {
        "part": "6 — Malícia",
        "kind": "principal",
        "name": "Behold the Glaive of Righteousness",
        "level": 79,
        "note": "Juramento com Liu Bei.",
    },
    {
        "part": "6 — Malícia",
        "kind": "sub",
        "name": "The Assault on Wuchao",
        "level": 80,
        "note": "",
    },
    {
        "part": "6 — Malícia",
        "kind": "sub",
        "name": "Let's Make Our Armor Shine!",
        "level": 83,
        "note": "",
    },
    {
        "part": "6 — Malícia",
        "kind": "sub",
        "name": "The Fearless Blade",
        "level": 84,
        "note": "",
    },
    {
        "part": "6 — Malícia",
        "kind": "principal",
        "name": "Decisive Battle of Guandu",
        "level": 85,
        "note": "Juramento com Yuan Shao.",
    },
    {
        "part": "6 — Malícia",
        "kind": "sub",
        "name": "Heirloom Seal of the Realm",
        "level": 88,
        "note": "",
    },
    {
        "part": "6 — Malícia",
        "kind": "sub",
        "name": "The Request of Goddess Luo",
        "level": 90,
        "note": "",
    },
    {
        "part": "7 — Ascensão",
        "kind": "principal",
        "name": "The Crouching Dragon Roars",
        "level": 93,
        "note": "Missão final: derrota o Yu Ji (Annihilator of Evil) e fecha a história (Open Eyes).",
    },
    {
        "part": "7 — Ascensão",
        "kind": "sub",
        "name": "The Two Walls Stand Tall",
        "level": 97,
        "note": "",
    },
    {
        "part": "7 — Ascensão",
        "kind": "sub",
        "name": "Let's Make Our Halberds Shine!",
        "level": 98,
        "note": "",
    },
    {
        "part": "7 — Ascensão",
        "kind": "sub",
        "name": "Pride of the Yuan Clan",
        "level": 99,
        "note": "",
    },
    {
        "part": "7 — Ascensão",
        "kind": "sub",
        "name": "The Crouching Dragon's Trial",
        "level": 100,
        "note": "",
    },
]

# 02 — 31 tábuas + 23 Shitieshou + 21 Cascas de Cigarra.
COLLECTIBLES = [
    {
        "kind": "Tábua",
        "name": "Yellow Turban Bandit's Note – Pt. 1",
        "mission": "The Village of Calamity",
        "where": "Ao lado da primeira Bandeira de Batalha.",
    },
    {
        "kind": "Tábua",
        "name": "Great Sage Mentor's Note",
        "mission": "The Demon Fort of the Yellow Heaven",
        "where": "Subindo a escada atrás da pira, no fim do nível: numa saliência à direita.",
    },
    {
        "kind": "Tábua",
        "name": "Despairing Taoist's Note",
        "mission": "In Search of the Immortal Wizard",
        "where": "Depois da 3ª bandeira, atravesse o bambuzal e escale as saliências.",
    },
    {
        "kind": "Tábua",
        "name": "Prisoner's Last Words",
        "mission": "Fall of the Corrupted Eunuch",
        "where": "Numa cela, pulando o muro perto da Bandeira de Batalha 2.",
    },
    {
        "kind": "Tábua",
        "name": "Magnate's Note",
        "mission": "Fall of the Corrupted Eunuch",
        "where": "Atrás de caixotes destrutíveis, na sala com escada depois da biblioteca de pergaminhos.",
    },
    {
        "kind": "Tábua",
        "name": "Sun Jian Soldier's Letter",
        "mission": "The Battle of Hulaoguan Pass",
        "where": "Na primeira tenda à esquerda ao entrar no acampamento.",
    },
    {
        "kind": "Tábua",
        "name": "Coalition General's Diary",
        "mission": "The Battle of Hulaoguan Pass",
        "where": "No meio do campo de batalha, num cadáver, onde você enfrenta o mini-chefe.",
    },
    {
        "kind": "Tábua",
        "name": "Luoyang Townswoman's Last Words",
        "mission": "Centuries of Glory Burned Away",
        "where": "À esquerda da 2ª Bandeira de Batalha, perto da emboscada do Honshu.",
    },
    {
        "kind": "Tábua",
        "name": "Colorfully Shining Well Writings",
        "mission": "Centuries of Glory Burned Away",
        "where": "Perto da ponte do laguinho, no pátio com o Demônio Cadáver.",
    },
    {
        "kind": "Tábua",
        "name": "Civil Officer's Last Words",
        "mission": "Centuries of Glory Burned Away",
        "where": "Suba no telhado perto da última Bandeira de Marcação e desça por dentro.",
    },
    {
        "kind": "Tábua",
        "name": "Brocade Sail Pirate's Scribblings",
        "mission": "Darkness Over the Hanshui River",
        "where": "No fundo do convés inferior do barco, depois de limpar o píer.",
    },
    {
        "kind": "Tábua",
        "name": "Xingyang Townswoman's Diary",
        "mission": "Darkness Over the Hanshui River",
        "where": "Dentro da casa à esquerda, depois do trecho da ponte quebrada.",
    },
    {
        "kind": "Tábua",
        "name": "Meiwu Fort Guard's Note",
        "mission": "Tyrant's Final Banquet",
        "where": "Siga pelos telhados após a Bandeira 2 até um canto.",
    },
    {
        "kind": "Tábua",
        "name": "Meiwu Fort Jailer's Note",
        "mission": "Tyrant's Final Banquet",
        "where": "No armário, subindo a partir da bifurcação da caverna.",
    },
    {
        "kind": "Tábua",
        "name": "Entertainer's Diary",
        "mission": "Tyrant's Final Banquet",
        "where": "Escale a cerca em frente à ponte, no jardim de bambu.",
    },
    {
        "kind": "Tábua",
        "name": "Entertainer's Scribblings – Pt. 1",
        "mission": "Fate of the Entertainer",
        "where": "Subindo a escada no jardim de bambu.",
    },
    {
        "kind": "Tábua",
        "name": "Entertainer's Scribblings – Pt. 2",
        "mission": "Fate of the Entertainer",
        "where": "A caminho do chefe, descendo a partir da Bandeira 3.",
    },
    {
        "kind": "Tábua",
        "name": "Indulgent Military Advisor's Diary",
        "mission": "The Uninhibited Heart",
        "where": "Ao lado da Bandeira de Batalha 2.",
    },
    {
        "kind": "Tábua",
        "name": "Cao Cao Soldier's Note",
        "mission": "Behold the Glaive of Righteousness",
        "where": "Depois de subir a escada e cruzar a ponte, na área de névoa.",
    },
    {
        "kind": "Tábua",
        "name": "Yan Liang's Note",
        "mission": "Behold the Glaive of Righteousness",
        "where": "Numa plataforma acima, na área corrompida com o Feiticeiro.",
    },
    {
        "kind": "Tábua",
        "name": "Tomb Robber's Letter",
        "mission": "Behold the Glaive of Righteousness",
        "where": "Na sala com um cristal vermelho na entrada, no trecho subterrâneo.",
    },
    {
        "kind": "Tábua",
        "name": "Disheartened Yuan Soldier's Note",
        "mission": "Decisive Battle of Guandu",
        "where": "Logo abaixo da Bandeira de Batalha 1, no caminho direto.",
    },
    {
        "kind": "Tábua",
        "name": "Yuan Zhao Assassin's Note",
        "mission": "Decisive Battle of Guandu",
        "where": "Numa casa, depois de limpar os inimigos junto aos galhos cristalizados.",
    },
    {
        "kind": "Tábua",
        "name": "Cao Cao Army Prisoner's Note",
        "mission": "Decisive Battle of Guandu",
        "where": "No ponto mais alto do acampamento, seguindo os galhos cristalizados.",
    },
    {
        "kind": "Tábua",
        "name": "Blindfolded Boy's Note – Pt. 1",
        "mission": "The Crouching Dragon Roars",
        "where": "Na casa atrás de você, no início da missão.",
    },
    {
        "kind": "Tábua",
        "name": "Blindfolded Boy's Note – Pt. 2",
        "mission": "The Crouching Dragon Roars",
        "where": "Na mesma casa da Pt. 1.",
    },
    {
        "kind": "Tábua",
        "name": "Frightened Merchant's Note",
        "mission": "The Crouching Dragon Roars",
        "where": "À vista, atravessando a vila.",
    },
    {
        "kind": "Tábua",
        "name": "Villager's Note",
        "mission": "The Crouching Dragon Roars",
        "where": "Todo à direita, passando da plataforma final.",
    },
    {
        "kind": "Tábua",
        "name": "Yellow Turban Bandit's Note – Pt. 2",
        "mission": "The Crouching Dragon Roars",
        "where": "Continuando escada acima.",
    },
    {
        "kind": "Tábua",
        "name": "Pining Woman's Note",
        "mission": "Vila Oculta do Monte Tianzhushan",
        "where": "Atrás de uma casa, à esquerda da Bandeira de Batalha.",
    },
    {
        "kind": "Tábua",
        "name": "Golden-Cicada-Obsessed Hermit's Scribblings",
        "mission": "Vila Oculta do Monte Tianzhushan",
        "where": "Aparece no mesmo telhado depois de entregar as 20 Cascas ao Eremita.",
    },
    {
        "kind": "Shitieshou",
        "name": "Shitieshou 01",
        "mission": "The Valley of Crying Wraiths",
        "where": "Depois de subir a escada e erguer a bandeira, desça a colina — fica à direita.",
    },
    {
        "kind": "Shitieshou",
        "name": "Shitieshou 02",
        "mission": "The Demon Fort of the Yellow Heaven",
        "where": "Dentro do prédio de canto cheio de potes e caixotes, na vila.",
    },
    {
        "kind": "Shitieshou",
        "name": "Shitieshou 03",
        "mission": "The Flying Swallow of Heishan",
        "where": "Antes de entrar na área do portão, à direita, junto às estruturas de madeira.",
    },
    {
        "kind": "Shitieshou",
        "name": "Shitieshou 04",
        "mission": "In Search of the Immortal Wizard",
        "where": "Ao lado da Bandeira de Batalha depois do lago com o Shuigui.",
    },
    {
        "kind": "Shitieshou",
        "name": "Shitieshou 05",
        "mission": "Shadow of the Sacred Mountain",
        "where": "Descendo a escada, num nicho de madeira à esquerda.",
    },
    {
        "kind": "Shitieshou",
        "name": "Shitieshou 06",
        "mission": "Fall of the Corrupted Eunuch",
        "where": "Volte e passe da ponte até outra saliência branca escalável; siga pelo telhado.",
    },
    {
        "kind": "Shitieshou",
        "name": "Shitieshou 07",
        "mission": "Escape from the Capital",
        "where": "Da Bandeira 2, entre na biblioteca de pergaminhos — fica na parte de cima.",
    },
    {
        "kind": "Shitieshou",
        "name": "Shitieshou 08",
        "mission": "The Battle of Hulaoguan Pass",
        "where": "Suba a muralha esquerda; no topo, vá à direita, no prédio em frente ao Zhuyan.",
    },
    {
        "kind": "Shitieshou",
        "name": "Shitieshou 09",
        "mission": "Centuries of Glory Burned Away",
        "where": "Num beco sem saída, em frente à Casca de Cigarra Dourada.",
    },
    {
        "kind": "Shitieshou",
        "name": "Shitieshou 10",
        "mission": "The Lost Sacred Artifact",
        "where": "Caia na água e siga por ela.",
    },
    {
        "kind": "Shitieshou",
        "name": "Shitieshou 11",
        "mission": "Darkness Over the Hanshui River",
        "where": "Nos prédios em frente à bandeira não corrompida, passando o portão guardado.",
    },
    {
        "kind": "Shitieshou",
        "name": "Shitieshou 12",
        "mission": "Tyrant's Final Banquet",
        "where": "Nas cavernas, na sala guardada pelo Zhupolong — bem onde ele está.",
    },
    {
        "kind": "Shitieshou",
        "name": "Shitieshou 13",
        "mission": "Fate of the Entertainer",
        "where": "Da Bandeira 2, no jardim de bambu, contorne pela esquerda passando a estátua.",
    },
    {
        "kind": "Shitieshou",
        "name": "Shitieshou 14",
        "mission": "War's Flames Blaze Fiercely",
        "where": "Num beco à esquerda depois de uma bandeira, com um soldado guardando.",
    },
    {
        "kind": "Shitieshou",
        "name": "Shitieshou 15",
        "mission": "The Uninhibited Heart",
        "where": "Use os pilares para chegar a um nicho escondido com uma escada longa; no topo.",
    },
    {
        "kind": "Shitieshou",
        "name": "Shitieshou 16",
        "mission": "The Way of the Warrior",
        "where": "Diagonalmente em frente à Bandeira de Batalha, numa saliência pequena.",
    },
    {
        "kind": "Shitieshou",
        "name": "Shitieshou 17",
        "mission": "Lu Bu, Mightiest Among Men",
        "where": "Em frente ao soldado com machado, numa plataforma atrás da estátua.",
    },
    {
        "kind": "Shitieshou",
        "name": "Shitieshou 18",
        "mission": "Behold the Glaive of Righteousness",
        "where": "Depois do Changgui e dos telhados, use as plataformas quebradas.",
    },
    {
        "kind": "Shitieshou",
        "name": "Shitieshou 19",
        "mission": "The Assault on Wuchao",
        "where": "Antes de uma bandeira, no mesmo corredor da luta contra o Leishi.",
    },
    {
        "kind": "Shitieshou",
        "name": "Shitieshou 20",
        "mission": "Let's Make Our Armor Shine!",
        "where": "Suba até o topo do barco depois de soltar a balsa.",
    },
    {
        "kind": "Shitieshou",
        "name": "Shitieshou 21",
        "mission": "Decisive Battle of Guandu",
        "where": "Depois da última bandeira pós-chefe, desça para a área de baixo.",
    },
    {
        "kind": "Shitieshou",
        "name": "Shitieshou 22",
        "mission": "Heirloom Seal of the Realm",
        "where": "Passe por dentro e vá até o extremo do outro lado.",
    },
    {
        "kind": "Shitieshou",
        "name": "Shitieshou 23",
        "mission": "Let's Make Our Halberds Shine!",
        "where": "No fim da vila, onde três cães o guardam.",
    },
    {
        "kind": "Casca",
        "name": "Casca 01",
        "mission": "Two Chivalrous Heroes",
        "where": "Depois do chefe Zhuyan, siga pelas falésias até entrar num prédio.",
    },
    {
        "kind": "Casca",
        "name": "Casca 02",
        "mission": "The Valley of Crying Wraiths",
        "where": "Depois da bandeira perto do Changgui, suba a falésia onde está o Feiticeiro.",
    },
    {
        "kind": "Casca",
        "name": "Casca 03",
        "mission": "The Demon Fort of the Yellow Heaven",
        "where": "Num telhado da vila, perto da escada de atalho.",
    },
    {
        "kind": "Casca",
        "name": "Casca 04",
        "mission": "In Search of the Immortal Wizard",
        "where": "Ao entrar na caverna de corrupção vermelha, ande pelo primeiro galho que vir.",
    },
    {
        "kind": "Casca",
        "name": "Casca 05",
        "mission": "Fall of the Corrupted Eunuch",
        "where": "Na parte iluminada da ponte, desça pela escada.",
    },
    {
        "kind": "Casca",
        "name": "Casca 06",
        "mission": "Fall of the Corrupted Eunuch",
        "where": "No telhado acima da bandeira, no pátio dos laguinhos.",
    },
    {
        "kind": "Casca",
        "name": "Casca 07",
        "mission": "The Battle of Hulaoguan Pass",
        "where": "Desça para o abismo — fica no fim.",
    },
    {
        "kind": "Casca",
        "name": "Casca 08",
        "mission": "Centuries of Glory Burned Away",
        "where": "Vá à esquerda de novo e passe do fogo.",
    },
    {
        "kind": "Casca",
        "name": "Casca 09",
        "mission": "Centuries of Glory Burned Away",
        "where": "Desça à esquerda até um nicho pequeno.",
    },
    {
        "kind": "Casca",
        "name": "Casca 10",
        "mission": "Darkness Over the Hanshui River",
        "where": "Desça do topo do naufrágio de madeira, no fim.",
    },
    {
        "kind": "Casca",
        "name": "Casca 11",
        "mission": "Tyrant's Final Banquet",
        "where": "Pelos telhados, num telhadinho acima da entrada.",
    },
    {
        "kind": "Casca",
        "name": "Casca 12",
        "mission": "Tyrant's Final Banquet",
        "where": "Suba até o ponto mais alto do telhado.",
    },
    {
        "kind": "Casca",
        "name": "Casca 13",
        "mission": "War's Flames Blaze Fiercely",
        "where": "À direita, e à direita de novo: um soldado com lança guardando um baú.",
    },
    {
        "kind": "Casca",
        "name": "Casca 14",
        "mission": "War's Flames Blaze Fiercely",
        "where": "Nos esgotos, sala com dois soldados de terracota sobre a plataforma guardando um baú.",
    },
    {
        "kind": "Casca",
        "name": "Casca 15",
        "mission": "The Way of the Warrior",
        "where": "Desça à esquerda e atravesse o riacho de lama até uma área lateral.",
    },
    {
        "kind": "Casca",
        "name": "Casca 16",
        "mission": "Lu Bu, Mightiest Among Men",
        "where": "Vá à esquerda — fica atrás de uma estrutura de madeira.",
    },
    {
        "kind": "Casca",
        "name": "Casca 17",
        "mission": "Behold the Glaive of Righteousness",
        "where": "Suba a escada longa atrás do Changgui e cruze a ponte.",
    },
    {
        "kind": "Casca",
        "name": "Casca 18",
        "mission": "Behold the Glaive of Righteousness",
        "where": "Atrás do cristal vermelho.",
    },
    {
        "kind": "Casca",
        "name": "Casca 19",
        "mission": "Decisive Battle of Guandu",
        "where": "Passe atrás do segundo, à direita, até uma saliência escondida.",
    },
    {
        "kind": "Casca",
        "name": "Casca 20",
        "mission": "Decisive Battle of Guandu",
        "where": "Desça para a área abaixo, atrás de um Shitieshou.",
    },
    {
        "kind": "Casca",
        "name": "Casca 21",
        "mission": "Vila Oculta do Monte Tianzhushan",
        "where": "Na base da torre mais alta da vila.",
    },
]

# 03 — Os 51 troféus do jogo base.
TROPHIES = [
    {
        "id": "plat",
        "name": "Wo Long",
        "tier": "platina",
        "requirement": "Obtenha todos os outros 50 troféus.",
        "shortcut": "Nenhum é perdível: toda missão pode ser refeita à vontade.",
        "image": "",
    },
    {
        "id": "t02",
        "name": "Open Eyes",
        "tier": "ouro",
        "requirement": "Ouça a decisão do Menino Vendado.",
        "shortcut": "Sai ao terminar a missão final, The Crouching Dragon Roars.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/ef7be662f29f55fe7b582e9ec29eba572220aacd.jpg",
    },
    {
        "id": "t03",
        "name": "Hunting the Great Deer",
        "tier": "ouro",
        "requirement": "Domine todas as batalhas principais e secundárias.",
        "shortcut": "As 46 missões: 16 principais + 30 secundárias. Use a aba Rota como checklist.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/4d7b313381837ebfc0f19c2b5fb2dfe20a6ae6f9.jpg",
    },
    {
        "id": "t04",
        "name": "Annihilator of Evil",
        "tier": "prata",
        "requirement": "Derrote Yu Ji.",
        "shortcut": "Chefe final da missão The Crouching Dragon Roars.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/44f970d3bb7ed1b71a3aca05116d6142682e4a04.jpg",
    },
    {
        "id": "t05",
        "name": "Adamantine",
        "tier": "prata",
        "requirement": "Melhore uma peça de armadura até a capacidade máxima.",
        "shortcut": "+9 na forja. Escolha uma peça barata e suba só ela.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/f9d40ae315063b26ef1e5765b00a39f8acd46765.jpg",
    },
    {
        "id": "t06",
        "name": "Keen-edged",
        "tier": "prata",
        "requirement": "Melhore uma arma até a capacidade máxima.",
        "shortcut": "+9 na forja. Vale a arma que você já usa.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/d2bbfdedca3d1abb5033f40d9c15b6d1d40c0f0b.jpg",
    },
    {
        "id": "t07",
        "name": "Ascension",
        "tier": "prata",
        "requirement": "Dê a quantidade máxima de Cascas de Cigarra Dourada.",
        "shortcut": "20 das 21 Cascas ao Eremita na torre mais alta da Vila Oculta. Ver aba Coletáveis.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/ccc33cdd80528faab55cf68d0196325123a6535d.jpg",
    },
    {
        "id": "t08",
        "name": "Battle-hardened",
        "tier": "prata",
        "requirement": "Domine 15 batalhas secundárias.",
        "shortcut": "Sai sozinho: são 30 no total e você precisa de todas para o Hunting the Great Deer.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/22801402bb34303611337706ca09ea3f89fccaf3.jpg",
    },
    {
        "id": "t09",
        "name": "Pots and Potions",
        "tier": "prata",
        "requirement": "Melhore o Pote de Cura do Dragão ao máximo.",
        "shortcut": "Suba capacidade e potência com Cristais de Veia de Dragão, na Vila Oculta.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/e9615857ea568381580e71e2a0a5aaa92fedb999.jpg",
    },
    {
        "id": "t10",
        "name": "Fly it High",
        "tier": "prata",
        "requirement": "Erga todas as Bandeiras de Batalha.",
        "shortcut": "São 145 bandeiras (Batalha + Marcação) somando as 46 missões. Ver aba Bandeiras.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/b24ea78d9642d16bb52d42531e1a35b7eca2ec22.jpg",
    },
    {
        "id": "t11",
        "name": "How Precious!",
        "tier": "prata",
        "requirement": "Alimente todos os Shitieshou.",
        "shortcut": "Os 23 pandas. Qualquer peça de equipamento serve para alimentar.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/736c00a8db372f39b2993da22d195ca68ed4b111.jpg",
    },
    {
        "id": "t12",
        "name": "Well-read",
        "tier": "prata",
        "requirement": "Colete todas as tábuas.",
        "shortcut": "As 31 tábuas. É o troféu mais raro do jogo. Ver aba Coletáveis.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/ecc38616d3ea942720a1a7bdcdee8888d4b38d08.jpg",
    },
    {
        "id": "t13",
        "name": "Wizardry Master",
        "tier": "prata",
        "requirement": "Aprenda todos os feitiços.",
        "shortcut": "Os 70 feitiços (14 por fase). Exige ter feito a missão Wizardry Spell Mastery.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/3df3d4b302c94f49a2788deadbee2acfa8c2e7c9.jpg",
    },
    {
        "id": "t14",
        "name": "Vow of the Stalwart",
        "tier": "bronze",
        "requirement": "Faça o juramento com Zhao Yun.",
        "shortcut": "Automático ao terminar Two Chivalrous Heroes.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/c43448a44aa1f3cb5984d29acbfac5b76cd33219.jpg",
    },
    {
        "id": "t15",
        "name": "Will of the Loyal",
        "tier": "bronze",
        "requirement": "Faça o juramento com Guan Yu e Zhang Fei.",
        "shortcut": "Automático ao terminar The Valley of Crying Wraiths.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/239975b93f44ba5d2fb16bdd3f78e7bf7b92226f.jpg",
    },
    {
        "id": "t16",
        "name": "Ambition of the Tiger",
        "tier": "bronze",
        "requirement": "Faça o juramento com Sun Jian.",
        "shortcut": "Automático ao terminar The Demon Fort of the Yellow Heaven.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/38b23e9c3f39a7aa6e0eaf6e5d1aaf446b4f615d.jpg",
    },
    {
        "id": "t17",
        "name": "Guardian of Peace",
        "tier": "bronze",
        "requirement": "Faça o juramento com Zuo Ci.",
        "shortcut": "Automático ao terminar In Search of the Immortal Wizard.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/6953d1d1f4dfe037d1b30487a6ed23b016260e2e.jpg",
    },
    {
        "id": "t18",
        "name": "Awakening of the Unscrupulous Hero",
        "tier": "bronze",
        "requirement": "Faça o juramento com Cao Cao.",
        "shortcut": "Automático ao terminar Fall of the Corrupted Eunuch. Há relatos de bug quando feito em co-op — faça essa missão SOZINHO.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/e68c6278a6124e0f201cc39957970c14a5a19b5a.jpg",
    },
    {
        "id": "t19",
        "name": "Guidance of the Constellations",
        "tier": "bronze",
        "requirement": "Faça o juramento com Lady Zhen.",
        "shortcut": "Automático ao terminar Centuries of Glory Burned Away.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/30cf073dbacdcd728d16d7b411d8ed93c8f710e8.jpg",
    },
    {
        "id": "t20",
        "name": "Succession",
        "tier": "bronze",
        "requirement": "Faça os juramentos com Sun Ce e Sun Quan.",
        "shortcut": "Automático ao terminar Darkness Over the Hanshui River.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/178e99e459290feba46fdb0a7167ac0edaccf422.jpg",
    },
    {
        "id": "t21",
        "name": "Familial Ties",
        "tier": "bronze",
        "requirement": "Faça o juramento com Hong Jing.",
        "shortcut": "Automático ao terminar Tyrant's Final Banquet.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/4ce94efb2bbba633fd24cfa618b6d4e261395435.jpg",
    },
    {
        "id": "t22",
        "name": "The Steadfast Duo",
        "tier": "bronze",
        "requirement": "Faça os juramentos com Xiahou Dun e Xiahou Yuan.",
        "shortcut": "Automático ao terminar War's Flames Blaze Fiercely.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/73aeebc67663501ecdf959d6b93d9fc058dd42f6.jpg",
    },
    {
        "id": "t23",
        "name": "Fearless Warrior",
        "tier": "bronze",
        "requirement": "Faça o juramento com Zhang Liao.",
        "shortcut": "Automático ao terminar The Way of the Warrior.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/086ad794c1496e9ba54684e9f619cbe588803784.jpg",
    },
    {
        "id": "t24",
        "name": "Entrusted Legacy",
        "tier": "bronze",
        "requirement": "Faça o juramento com Lu Bu.",
        "shortcut": "Automático ao terminar Lu Bu, Mightiest Among Men.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/0d94c48593b1bb35d7efc096e4a807463e61f8d1.jpg",
    },
    {
        "id": "t25",
        "name": "Aspiration and Amity",
        "tier": "bronze",
        "requirement": "Faça o juramento com Liu Bei.",
        "shortcut": "Automático ao terminar Behold the Glaive of Righteousness.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/1cf7e834978ceb533131dfc080ad990cc6e4b002.jpg",
    },
    {
        "id": "t26",
        "name": "Dreams of Unity",
        "tier": "bronze",
        "requirement": "Faça o juramento com Yuan Shao.",
        "shortcut": "Automático ao terminar Decisive Battle of Guandu.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/0e8600845870238c5076922c0ae331641333739c.jpg",
    },
    {
        "id": "t27",
        "name": "Journey's Beginning",
        "tier": "bronze",
        "requirement": "Desperte do sono da morte.",
        "shortcut": "Automático no começo do jogo.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/eceaca0f379d8821934108b90b34d93168cf0fc9.jpg",
    },
    {
        "id": "t28",
        "name": "Staunching Heresy",
        "tier": "bronze",
        "requirement": "Derrote todos os Feiticeiros que fazem o ritual.",
        "shortcut": "Em The Valley of Crying Wraiths: não corra para o chefe, limpe os feiticeiros antes.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/5f68232e65afdb615ed8a696f6a93d8263458c72.jpg",
    },
    {
        "id": "t29",
        "name": "Dogged Justice",
        "tier": "bronze",
        "requirement": "Salve os eremitas capturados.",
        "shortcut": "Em Fall of the Corrupted Eunuch: liberte-os antes de terminar a missão.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/2099dc7fe7e3b1c5b674656bbee07db4a825037c.jpg",
    },
    {
        "id": "t30",
        "name": "Mightiest of Men",
        "tier": "bronze",
        "requirement": "Repila as forças de Lu Bu.",
        "shortcut": "Em The Battle of Hulaoguan Pass: sobreviva ao encontro com o Lu Bu.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/3cc22c370bd1bd80c7fb4fa59aefcff57d16698b.jpg",
    },
    {
        "id": "t31",
        "name": "Strung Bow",
        "tier": "bronze",
        "requirement": "Derrote 5 inimigos com uma balista.",
        "shortcut": "Em The Battle of Hulaoguan Pass: use as balistas da muralha.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/36316fd42aa347d4f2b2419af0f406f88fd99021.jpg",
    },
    {
        "id": "t32",
        "name": "Heroes will Rise",
        "tier": "bronze",
        "requirement": "Repila o Xielong.",
        "shortcut": "Em Centuries of Glory Burned Away.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/7f0a439a029dad65f150bc47e7b27168e14b1bc1.jpg",
    },
    {
        "id": "t33",
        "name": "At Fifteen I Joined the Army",
        "tier": "bronze",
        "requirement": "Chegue ao nível 15.",
        "shortcut": "Sai sozinho ainda na Parte 2.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/2b9072d02e0bb2f71315c1805dc19b7f258e92a1.jpg",
    },
    {
        "id": "t34",
        "name": "Only at Eighty Did I Finally Return",
        "tier": "bronze",
        "requirement": "Chegue ao nível 80.",
        "shortcut": "Sai sozinho: as últimas missões pedem nível 90+.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/99f1d3cf321b61298ebe72e3ab4b019631895af7.jpg",
    },
    {
        "id": "t35",
        "name": "Best Flag Forward",
        "tier": "bronze",
        "requirement": "Erga sua primeira Bandeira de Batalha.",
        "shortcut": "Primeiros minutos de jogo.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/640b5a283e176f960c17b31fd7e535fa5803b6f3.jpg",
    },
    {
        "id": "t36",
        "name": "Wizardry Beginner",
        "tier": "bronze",
        "requirement": "Aprenda seu primeiro feitiço.",
        "shortcut": "Numa bandeira: Feitiços → Aprender.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/3b944ecdefaa62d9405280ecfb5ae1bf2b9792d9.jpg",
    },
    {
        "id": "t37",
        "name": "First Phase",
        "tier": "bronze",
        "requirement": "Interaja com as Cinco Fases pela primeira vez.",
        "shortcut": "Não é só lançar feitiços: use um feitiço que ANULA o elemento oposto do inimigo (ex.: Metal cancela Raio).",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/922747d2338265d5b3f2039428e694538b450bcc.jpg",
    },
    {
        "id": "t38",
        "name": "Unstoppable",
        "tier": "bronze",
        "requirement": "Chegue ao Rank de Moral 20 numa batalha.",
        "shortcut": "Erga todas as bandeiras da missão e mate inimigos sem morrer. Fica fácil numa missão antiga com sua Fortitude alta.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/a7dbaa1c7e8a89d89bb28e38a912cfea1ea9a47b.jpg",
    },
    {
        "id": "t39",
        "name": "How Cute!",
        "tier": "bronze",
        "requirement": "Alimente seu primeiro Shitieshou.",
        "shortcut": "O primeiro está em The Valley of Crying Wraiths.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/b63529d255c993035fc3c4f967353f56493cc2c8.jpg",
    },
    {
        "id": "t40",
        "name": "Craftsmanship",
        "tier": "bronze",
        "requirement": "Melhore sua primeira peça de equipamento.",
        "shortcut": "Na forja da Vila Oculta.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/0ebc63218848640d4801721f33da9b2a2132e06c.jpg",
    },
    {
        "id": "t41",
        "name": "All that Glitters",
        "tier": "bronze",
        "requirement": "Encaixe sua primeira joia na forja.",
        "shortcut": "Na forja: Encaixar.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/ef23cff733b30b662755cbf950b9c9c657c0041e.jpg",
    },
    {
        "id": "t42",
        "name": "Decor Maketh the Man",
        "tier": "bronze",
        "requirement": "Decore seu primeiro item na forja.",
        "shortcut": "Na forja: Decorar. Só muda a aparência.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/6b1f1a3af6cb6e906cb0a346ebe95c45e492081f.jpg",
    },
    {
        "id": "t43",
        "name": "Fantastic Form",
        "tier": "bronze",
        "requirement": "Equipe um conjunto completo de 4 estrelas.",
        "shortcut": "Arma corpo a corpo + arma à distância + 1 acessório + 4 peças de armadura, todos 4 estrelas.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/ae2af9a47c65ba3e5eb10342c2e1ce4b9bbcdc2a.jpg",
    },
    {
        "id": "t44",
        "name": "Sharp Reflexes",
        "tier": "bronze",
        "requirement": "Desvie com sucesso de 10 golpes críticos.",
        "shortcut": "Os ataques vermelhos (Golpe Fatal). Sai sozinho, é a mecânica central do jogo.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/72d96a140ea3efaf27dabc78f7c5947c7a5a9612.jpg",
    },
    {
        "id": "t45",
        "name": "Vulnerable Moments",
        "tier": "bronze",
        "requirement": "Acerte 50 Golpes Fatais.",
        "shortcut": "O contra-ataque depois de quebrar o Espírito do inimigo. Sai sozinho.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/165dc078699ffe8537ded23f0b28a137a635a893.jpg",
    },
    {
        "id": "t46",
        "name": "Righteous Judgment",
        "tier": "bronze",
        "requirement": "Vingue-se 10 vezes.",
        "shortcut": "Mate o inimigo que te matou (ele fica com uma marca). Sai sozinho quando você morre.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/a7d7da49b59d43d04aca5673f767225050beb136.jpg",
    },
    {
        "id": "t47",
        "name": "Eye for an Eye",
        "tier": "bronze",
        "requirement": "Repila invasores 10 vezes.",
        "shortcut": "Só invasores NPC contam. Desative a invasão de jogadores nas opções para garantir.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/4f2f9f2f9b1610ac459bb89f8fe2144f3abd57cc.jpg",
    },
    {
        "id": "t48",
        "name": "Side by Side",
        "tier": "bronze",
        "requirement": "Domine 10 batalhas com um companheiro.",
        "shortcut": "Chame um reforço na bandeira antes de iniciar. Faça sempre — ajuda e conta.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/52350473647fd406fbe92f6f5d5382f55e9cb027.jpg",
    },
    {
        "id": "t49",
        "name": "Call to Arms",
        "tier": "bronze",
        "requirement": "Use 10 Selos do Tigre.",
        "shortcut": "Selos de recrutamento, usados na bandeira para chamar reforços.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/3968a3226408e3dd5786c07a34cdb1081b17e2cb.jpg",
    },
    {
        "id": "t50",
        "name": "Great Gatherings",
        "tier": "bronze",
        "requirement": "Junte forças com todos os guerreiros disponíveis.",
        "shortcut": "Chame cada um dos 17 pelo menos uma vez. Ver aba Companheiros para o método rápido.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/04bfbb5d8bc19561fa72604c9afcd17339cfec1e.jpg",
    },
    {
        "id": "t51",
        "name": "Merit Beyond Measure",
        "tier": "bronze",
        "requirement": "Receba a bênção de um irmão de juramento.",
        "shortcut": "Suba o Juramento de um companheiro até o nível 10 e resgate a bênção numa bandeira.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/0306f61755667f0aaf78783548b2f676df5fc1e8.jpg",
    },
]

# 05 — Os 17 guerreiros recrutáveis.
COMPANIONS = [
    {
        "name": "Zhao Yun",
        "when": "Two Chivalrous Heroes (Parte 2)",
    },
    {
        "name": "Guan Yu",
        "when": "The Valley of Crying Wraiths (Parte 2)",
    },
    {
        "name": "Zhang Fei",
        "when": "The Valley of Crying Wraiths (Parte 2)",
    },
    {
        "name": "Sun Jian",
        "when": "The Demon Fort of the Yellow Heaven (Parte 2)",
    },
    {
        "name": "Cao Cao",
        "when": "Fall of the Corrupted Eunuch (Parte 3)",
    },
    {
        "name": "Zhang Jiao",
        "when": "Ao longo da campanha",
    },
    {
        "name": "Xun Yu",
        "when": "Ao longo da campanha",
    },
    {
        "name": "Hong Jing",
        "when": "Tyrant's Final Banquet (Parte 4)",
    },
    {
        "name": "Sun Ce",
        "when": "Darkness Over the Hanshui River (Parte 4)",
    },
    {
        "name": "Sun Quan",
        "when": "Darkness Over the Hanshui River (Parte 4)",
    },
    {
        "name": "Han Dang",
        "when": "Missões do clã Sun (Parte 4)",
    },
    {
        "name": "Cheng Pu",
        "when": "Missões do clã Sun (Parte 4)",
    },
    {
        "name": "Huang Gai",
        "when": "Missões do clã Sun (Parte 4)",
    },
    {
        "name": "Xiahou Dun",
        "when": "War's Flames Blaze Fiercely (Parte 5)",
    },
    {
        "name": "Xiahou Yuan",
        "when": "War's Flames Blaze Fiercely (Parte 5)",
    },
    {
        "name": "Zhang Liao",
        "when": "The Way of the Warrior (Parte 5)",
    },
    {
        "name": "Liu Bei",
        "when": "Behold the Glaive of Righteousness (Parte 6)",
    },
]

# 06 — As Cinco Fases (14 feitiços cada = 70).
PHASES = [
    {
        "name": "Madeira (Wood)",
        "spells": "14 feitiços",
        "note": "Cura e suporte. Anula a Terra.",
    },
    {
        "name": "Fogo (Fire)",
        "spells": "14 feitiços",
        "note": "Dano direto e queimadura. Anula o Metal.",
    },
    {
        "name": "Terra (Earth)",
        "spells": "14 feitiços",
        "note": "Defesa e controle. Anula a Água.",
    },
    {
        "name": "Metal (Metal)",
        "spells": "14 feitiços",
        "note": "Raio e perfuração. Anula a Madeira.",
    },
    {
        "name": "Água (Water)",
        "spells": "14 feitiços",
        "note": "Furtividade e gelo. Anula o Fogo.",
    },
]

# 07 — Preparo e equipamento.
PREP = [
    {
        "name": "Desativar invasão de jogadores",
        "when": "Antes de tudo",
        "why": "O Eye for an Eye só conta invasores NPC. Com a invasão de jogadores ligada, um jogador real pode entrar no lugar do NPC e a contagem não anda.",
    },
    {
        "name": "Fazer Fall of the Corrupted Eunuch sozinho",
        "when": "Parte 3",
        "why": "O juramento com Cao Cao (Awakening of the Unscrupulous Hero) tem relatos de bug quando a missão é feita em co-op.",
    },
    {
        "name": "Sempre chamar um reforço antes de iniciar a missão",
        "when": "Toda missão",
        "why": "Conta para Side by Side (10 batalhas) e sobe o Juramento do companheiro, que é o que libera o Merit Beyond Measure. Não custa nada e você faria mesmo assim.",
    },
    {
        "name": "Erguer TODAS as bandeiras de cada missão na primeira visita",
        "when": "Toda missão",
        "why": "As Bandeiras de Marcação sobem sua Fortitude, que é o piso do seu Rank de Moral. Quanto mais bandeiras, mais forte você entra na missão seguinte — e é o Fly it High saindo de graça em vez de virar limpeza no fim.",
    },
    {
        "name": "Fazer a missão Wizardry Spell Mastery",
        "when": "Parte 3, nível 32",
        "why": "É ela que libera os feitiços de tier alto. Sem ela o Wizardry Master fica impossível, e muita gente só descobre isso no fim.",
    },
    {
        "name": "Subir uma arma até +9",
        "when": "Quando tiver materiais",
        "why": "Keen-edged. Escolha a arma que você usa de verdade.",
    },
    {
        "name": "Subir uma peça de armadura até +9",
        "when": "Quando tiver materiais",
        "why": "Adamantine. Pode ser a peça mais barata.",
    },
    {
        "name": "Melhorar o Pote de Cura do Dragão ao máximo",
        "when": "Ao longo do jogo",
        "why": "Pots and Potions. Use os Cristais e Essências de Veia de Dragão que você encontra nas missões — eles não servem para mais nada.",
    },
    {
        "name": "Montar um conjunto 4 estrelas completo",
        "when": "Fim do jogo",
        "why": "Fantastic Form: arma corpo a corpo, arma à distância, 1 acessório e 4 peças de armadura, todos 4 estrelas.",
    },
    {
        "name": "Entregar as 20 Cascas ao Eremita",
        "when": "Depois de coletar",
        "why": "Ascension. Ele fica na torre mais alta da Vila Oculta. Faça backup do save antes de entregar a última.",
    },
]

# 08 — Imagens de referência.
VISUALS = [
    {
        "title": "Bandeiras e Moral",
        "caption": "Bandeira de Batalha é checkpoint e sobe a Moral; Bandeira de Marcação sobe a Fortitude, que é o piso da Moral naquela missão.",
        "image": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1448440/ss_db17363dfa15e14909f975ff768c666e2fe98f63.1920x1080.jpg",
        "source": "Steam / KOEI TECMO",
    },
    {
        "title": "Desvio de Golpe Fatal",
        "caption": "O desvio no ataque vermelho é a mecânica central: alimenta Sharp Reflexes e abre os Golpes Fatais do Vulnerable Moments.",
        "image": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1448440/ss_46d32690392bad490af693cbf3394f8f346890ce.1920x1080.jpg",
        "source": "Steam / KOEI TECMO",
    },
    {
        "title": "As Cinco Fases",
        "caption": "Cada fase anula outra (Metal anula Madeira, Fogo anula Metal, Água anula Fogo, Terra anula Água, Madeira anula Terra). O First Phase pede essa anulação, não só lançar feitiços.",
        "image": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1448440/ss_616f77c0cf7aa9ad801608d72bbaf188696b7438.1920x1080.jpg",
        "source": "Steam / KOEI TECMO",
    },
    {
        "title": "Companheiros",
        "caption": "Chamar um reforço antes de cada missão sobe o Juramento dele e conta para o Side by Side.",
        "image": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1448440/ss_059a719c1e150ec703459541db853fd2fbf1df55.1920x1080.jpg",
        "source": "Steam / KOEI TECMO",
    },
    {
        "title": "Chefes",
        "caption": "Com a Fortitude alta por ter erguido todas as bandeiras, os chefes entram bem abaixo do seu Rank de Moral.",
        "image": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1448440/ss_36a81a85d8f775a29d410d398c59686e81d0c303.1920x1080.jpg",
        "source": "Steam / KOEI TECMO",
    },
    {
        "title": "Exploração",
        "caption": "Tábuas, Shitieshou e Cascas brilham em dourado no chão. Vale explorar telhados e becos antes de puxar o chefe.",
        "image": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1448440/ss_cd96ce49fcf8ce741662d8535e44bdaa17a98378.1920x1080.jpg",
        "source": "Steam / KOEI TECMO",
    },
    {
        "title": "Forja",
        "caption": "Onde saem Craftsmanship, All that Glitters, Decor Maketh the Man, Keen-edged e Adamantine.",
        "image": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1448440/ss_8a5b4063c83ad2216a23134511fe2ab8bb8c06cf.1920x1080.jpg",
        "source": "Steam / KOEI TECMO",
    },
    {
        "title": "Campanha",
        "caption": "São 16 batalhas principais e 30 secundárias — 46 no total para o Hunting the Great Deer.",
        "image": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1448440/ss_94092c0b508bf16f90ece74338dae524d6f00a35.1920x1080.jpg",
        "source": "Steam / KOEI TECMO",
    },
]

# 09 — Fontes consultadas.
SOURCES = [
    {
        "title": "PowerPyx — Wo Long: Fallen Dynasty Trophy Guide & Roadmap",
        "url": "https://www.powerpyx.com/wo-long-fallen-dynasty-trophy-guide-roadmap/",
        "note": "Roteiro geral, avisos de bug (Cao Cao em co-op, Eye for an Eye) e a lista dos 17 companheiros.",
    },
    {
        "title": "PowerPyx — All Tablet / Shitieshou / Golden Cicada Shell Locations",
        "url": "https://www.powerpyx.com/wo-long-fallen-dynasty-all-collectible-locations/",
        "note": "As 31 tábuas, os 23 Shitieshou e as 21 Cascas com missão e local — base da aba Coletáveis.",
    },
    {
        "title": "Fextralife — Wo Long Trophy & Achievement Guide",
        "url": "https://wolong.wiki.fextralife.com/Trophy+&+Achievement+Guide",
        "note": "Lista dos 51 troféus com os tiers conferidos (1 platina, 2 ouro, 10 prata, 38 bronze).",
    },
    {
        "title": "Game8 — List of Missions",
        "url": "https://game8.co/games/Wo-Long-Fallen-Dynasty/archives/406772",
        "note": "As 46 batalhas separadas por parte, com o nível recomendado de cada uma.",
    },
    {
        "title": "Fextralife — Great Gatherings / Wizardry Master",
        "url": "https://wolong.wiki.fextralife.com/Great+Gatherings",
        "note": "Método rápido dos 17 companheiros e o pré-requisito da missão Wizardry Spell Mastery.",
    },
    {
        "title": "PSNProfiles — Wo Long: Fallen Dynasty",
        "url": "https://psnprofiles.com/trophies/21250-wo-long-fallen-dynasty",
        "note": "Conferência da divisão oficial dos troféus e das raridades.",
    },
]

# Rodapé do guia.
FOOTER = "Wo Long: Fallen Dynasty — Platina PT-BR • guia não oficial • progresso salvo em %APPDATA%/StreamerSidekick/platinas/wolong/"

