"""Dados do guia de platina de Wo Long: Fallen Dynasty (jogo base, PT-BR).

Estrutura centrada na missão: as 46 batalhas são a espinha do guia e cada uma
carrega os próprios troféus e coletáveis. 75 coletáveis com foto e
descrição, 51 troféus, 8 passos de fecho e 5 hábitos de preparo.

Este é o ÚNICO arquivo específico do jogo — os demais módulos são genéricos.
"""

# Identificador único do guia (kebab-case): vira o id do plugin e a pasta
# de progresso em %APPDATA%/StreamerSidekick/platinas/<id>/.
GUIDE_ID = "wolong"

GAME_NAME = "Wo Long — Platina"
GAME_SUBTITLE = (
    "Guia PT-BR do jogo base: as 46 batalhas na ordem, cada uma com seus troféus "
    "e coletáveis com foto."
)
ACCENT = "#C8102E"  # vermelho da identidade do jogo

HERO_IMAGE = "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1448440/header.jpg"

# Parágrafo de abertura.
INTRO = "São 51 troféus, nenhum perdível e uma run só — cerca de 40 horas. Tudo em Wo Long acontece dentro de uma batalha, então o guia é uma lista de batalhas: abra a que você vai jogar e ela mostra os troféus que saem ali, a caixa das bandeiras e cada coletável com foto e descrição. Erguer todas as bandeiras não é coleção: a Fortitude que elas dão é o piso do seu Rank de Moral, então quem coleta fica mais forte a cada missão."

# Números de destaque exibidos no topo.
HERO_STATS = [
    {
        "value": "51",
        "label": "troféus",
    },
    {
        "value": "46",
        "label": "batalhas",
    },
    {
        "value": "75",
        "label": "coletáveis com foto",
    },
    {
        "value": "145",
        "label": "bandeiras",
    },
    {
        "value": "1 run",
        "label": "sem nada perdível",
    },
]

# As 4 abas do guia.
SECTIONS = [
    {
        "key": "battles",
        "num": "01",
        "nav": "Batalhas",
        "eyebrow": "O guia",
        "title": "As 46 batalhas, na ordem",
        "lead": "Cada batalha traz o que ela dá de troféu, a caixa das bandeiras e os coletáveis dela com foto e descrição. É a única aba que você precisa com o jogo aberto.",
        "notices": [
            {
                "tone": "red",
                "text": "A rotina de toda batalha: chame um reforço → erga TODAS as bandeiras → pegue os coletáveis listados no card → só então vá ao chefe. Bandeira de Marcação sobe a Fortitude, que é o piso do seu Rank de Moral: quem ergue tudo entra na batalha seguinte mais forte; quem ignora apanha no meio do jogo e ainda termina com 145 bandeiras para refazer.",
            },
            {
                "tone": "info",
                "text": "Antes da primeira missão, dois ajustes: desative a invasão por jogadores (o Eye for an Eye só conta NPC) e jogue Fall of the Corrupted Eunuch sozinho (o juramento com Cao Cao bugava em co-op).",
            },
        ],
    },
    {
        "key": "trophies",
        "num": "02",
        "nav": "51 Troféus",
        "eyebrow": "Platina",
        "title": "Os 51 troféus do jogo base",
        "lead": "1 platina, 2 ouro, 10 prata e 38 bronze. Nenhum é perdível.",
        "notices": [
            {
                "tone": "info",
                "text": "As DLCs (Battle of Zhongyuan, Conqueror of Jiangdong e Upheaval in Jingxiang) têm listas separadas e não contam para esta platina.",
            },
        ],
    },
    {
        "key": "systems",
        "num": "03",
        "nav": "Sistemas",
        "eyebrow": "Feitiços, companheiros e preparo",
        "title": "O que não cabe dentro de uma batalha",
        "lead": "As Cinco Fases, os 17 companheiros e os hábitos que decidem se a platina é uma run ou duas.",
        "notices": [],
    },
    {
        "key": "sources",
        "num": "04",
        "nav": "Fontes",
        "eyebrow": "Pesquisa cruzada",
        "title": "Fontes do guia",
        "lead": "A rota foi montada cruzando estes guias. As fotos dos coletáveis são do PowerPyx.",
        "notices": [],
    },
]

# 01 — As 46 batalhas (16 principais + 30 secundárias), na ordem de jogo.
MISSIONS = [
    {
        "part": "1 — Encontro",
        "kind": "principal",
        "name": "The Village of Calamity",
        "level": 1,
        "trophies": [
            "Journey's Beginning",
            "Best Flag Forward",
        ],
        "note": "Tutorial. Volte aqui no fim da run: é a missão mais curta para chamar os 17 companheiros do Great Gatherings.",
    },
    {
        "part": "2 — Ilusão",
        "kind": "principal",
        "name": "Two Chivalrous Heroes",
        "level": 5,
        "trophies": [
            "Vow of the Stalwart",
        ],
        "note": "",
    },
    {
        "part": "2 — Ilusão",
        "kind": "sub",
        "name": "The Yellow Heaven Burns",
        "level": 10,
        "trophies": [],
        "note": "",
    },
    {
        "part": "2 — Ilusão",
        "kind": "principal",
        "name": "The Valley of Crying Wraiths",
        "level": 11,
        "trophies": [
            "Will of the Loyal",
            "Staunching Heresy",
            "How Cute!",
        ],
        "note": "Não corra para o chefe: mate TODOS os feiticeiros que fazem o ritual antes, senão perde o Staunching Heresy nesta passagem.",
    },
    {
        "part": "2 — Ilusão",
        "kind": "sub",
        "name": "Tale of Guiguzi",
        "level": 13,
        "trophies": [],
        "note": "",
    },
    {
        "part": "2 — Ilusão",
        "kind": "principal",
        "name": "The Demon Fort of the Yellow Heaven",
        "level": 17,
        "trophies": [
            "Ambition of the Tiger",
        ],
        "note": "",
    },
    {
        "part": "2 — Ilusão",
        "kind": "sub",
        "name": "The Flying Swallow of Heishan",
        "level": 20,
        "trophies": [],
        "note": "",
    },
    {
        "part": "3 — Corrupção",
        "kind": "principal",
        "name": "In Search of the Immortal Wizard",
        "level": 25,
        "trophies": [
            "Guardian of Peace",
        ],
        "note": "",
    },
    {
        "part": "3 — Corrupção",
        "kind": "sub",
        "name": "Shadow of the Sacred Mountain",
        "level": 27,
        "trophies": [],
        "note": "",
    },
    {
        "part": "3 — Corrupção",
        "kind": "principal",
        "name": "Fall of the Corrupted Eunuch",
        "level": 29,
        "trophies": [
            "Awakening of the Unscrupulous Hero",
            "Dogged Justice",
        ],
        "note": "Jogue esta missão SOZINHO: o juramento com Cao Cao tem relatos de não estourar quando ela é feita em co-op. Liberte os eremitas presos antes de terminar.",
    },
    {
        "part": "3 — Corrupção",
        "kind": "sub",
        "name": "Wizardry Spell Mastery",
        "level": 32,
        "trophies": [],
        "note": "A batalha mais importante do guia: é ela que libera os feitiços de tier alto. Sem ela o Wizardry Master fica impossível — não pule.",
    },
    {
        "part": "3 — Corrupção",
        "kind": "sub",
        "name": "Escape from the Capital",
        "level": 33,
        "trophies": [],
        "note": "",
    },
    {
        "part": "3 — Corrupção",
        "kind": "sub",
        "name": "The Valorous Trio",
        "level": 35,
        "trophies": [],
        "note": "",
    },
    {
        "part": "4 — Tirania",
        "kind": "principal",
        "name": "The Battle of Hulaoguan Pass",
        "level": 37,
        "trophies": [
            "Mightiest of Men",
            "Strung Bow",
        ],
        "note": "Use as balistas da muralha para matar 5 inimigos (Strung Bow) antes de avançar.",
    },
    {
        "part": "4 — Tirania",
        "kind": "sub",
        "name": "Like Father, Like Son",
        "level": 41,
        "trophies": [],
        "note": "",
    },
    {
        "part": "4 — Tirania",
        "kind": "principal",
        "name": "Centuries of Glory Burned Away",
        "level": 43,
        "trophies": [
            "Guidance of the Constellations",
            "Heroes will Rise",
        ],
        "note": "",
    },
    {
        "part": "4 — Tirania",
        "kind": "sub",
        "name": "The Lost Sacred Artifact",
        "level": 45,
        "trophies": [],
        "note": "",
    },
    {
        "part": "4 — Tirania",
        "kind": "principal",
        "name": "Darkness Over the Hanshui River",
        "level": 49,
        "trophies": [
            "Succession",
        ],
        "note": "",
    },
    {
        "part": "4 — Tirania",
        "kind": "sub",
        "name": "The Tiger's Loyal Subjects",
        "level": 53,
        "trophies": [],
        "note": "",
    },
    {
        "part": "4 — Tirania",
        "kind": "principal",
        "name": "Tyrant's Final Banquet",
        "level": 55,
        "trophies": [
            "Familial Ties",
        ],
        "note": "",
    },
    {
        "part": "4 — Tirania",
        "kind": "sub",
        "name": "Fate of the Entertainer",
        "level": 57,
        "trophies": [],
        "note": "",
    },
    {
        "part": "4 — Tirania",
        "kind": "sub",
        "name": "Realm of Battle",
        "level": 57,
        "trophies": [],
        "note": "",
    },
    {
        "part": "4 — Tirania",
        "kind": "sub",
        "name": "Zhao Yun's Exile",
        "level": 57,
        "trophies": [],
        "note": "",
    },
    {
        "part": "4 — Tirania",
        "kind": "sub",
        "name": "Massacre of Meiwu Fort",
        "level": 58,
        "trophies": [],
        "note": "",
    },
    {
        "part": "4 — Tirania",
        "kind": "sub",
        "name": "The Unparalleled Spear",
        "level": 59,
        "trophies": [],
        "note": "",
    },
    {
        "part": "4 — Tirania",
        "kind": "sub",
        "name": "Green Plum, Warm Liquor",
        "level": 60,
        "trophies": [],
        "note": "",
    },
    {
        "part": "5 — Fortitude",
        "kind": "principal",
        "name": "War's Flames Blaze Fiercely",
        "level": 61,
        "trophies": [
            "The Steadfast Duo",
        ],
        "note": "",
    },
    {
        "part": "5 — Fortitude",
        "kind": "sub",
        "name": "The Uninhibited Heart",
        "level": 62,
        "trophies": [],
        "note": "",
    },
    {
        "part": "5 — Fortitude",
        "kind": "principal",
        "name": "The Way of the Warrior",
        "level": 67,
        "trophies": [
            "Fearless Warrior",
        ],
        "note": "",
    },
    {
        "part": "5 — Fortitude",
        "kind": "sub",
        "name": "Caliber of a Hero",
        "level": 69,
        "trophies": [],
        "note": "",
    },
    {
        "part": "5 — Fortitude",
        "kind": "sub",
        "name": "Legend of the Thunder God",
        "level": 71,
        "trophies": [],
        "note": "",
    },
    {
        "part": "5 — Fortitude",
        "kind": "principal",
        "name": "Lu Bu, Mightiest Among Men",
        "level": 73,
        "trophies": [
            "Entrusted Legacy",
        ],
        "note": "",
    },
    {
        "part": "5 — Fortitude",
        "kind": "sub",
        "name": "The Scarlet Crystal",
        "level": 76,
        "trophies": [],
        "note": "",
    },
    {
        "part": "5 — Fortitude",
        "kind": "sub",
        "name": "Preachers of the Dark Path",
        "level": 77,
        "trophies": [],
        "note": "",
    },
    {
        "part": "6 — Malícia",
        "kind": "principal",
        "name": "Behold the Glaive of Righteousness",
        "level": 79,
        "trophies": [
            "Aspiration and Amity",
        ],
        "note": "Concentra 6 coletáveis, vários no mesmo trecho de névoa depois do Changgui — vale limpar a área inteira antes de seguir.",
    },
    {
        "part": "6 — Malícia",
        "kind": "sub",
        "name": "The Assault on Wuchao",
        "level": 80,
        "trophies": [],
        "note": "",
    },
    {
        "part": "6 — Malícia",
        "kind": "sub",
        "name": "Let's Make Our Armor Shine!",
        "level": 83,
        "trophies": [],
        "note": "",
    },
    {
        "part": "6 — Malícia",
        "kind": "sub",
        "name": "The Fearless Blade",
        "level": 84,
        "trophies": [],
        "note": "",
    },
    {
        "part": "6 — Malícia",
        "kind": "principal",
        "name": "Decisive Battle of Guandu",
        "level": 85,
        "trophies": [
            "Dreams of Unity",
        ],
        "note": "",
    },
    {
        "part": "6 — Malícia",
        "kind": "sub",
        "name": "Heirloom Seal of the Realm",
        "level": 88,
        "trophies": [],
        "note": "",
    },
    {
        "part": "6 — Malícia",
        "kind": "sub",
        "name": "The Request of Goddess Luo",
        "level": 90,
        "trophies": [],
        "note": "",
    },
    {
        "part": "7 — Ascensão",
        "kind": "principal",
        "name": "The Crouching Dragon Roars",
        "level": 93,
        "trophies": [
            "Annihilator of Evil",
            "Open Eyes",
        ],
        "note": "Missão final. Tem 5 tábuas — pegue todas antes de encarar o Yu Ji.",
    },
    {
        "part": "7 — Ascensão",
        "kind": "sub",
        "name": "The Two Walls Stand Tall",
        "level": 97,
        "trophies": [],
        "note": "",
    },
    {
        "part": "7 — Ascensão",
        "kind": "sub",
        "name": "Let's Make Our Halberds Shine!",
        "level": 98,
        "trophies": [],
        "note": "",
    },
    {
        "part": "7 — Ascensão",
        "kind": "sub",
        "name": "Pride of the Yuan Clan",
        "level": 99,
        "trophies": [],
        "note": "",
    },
    {
        "part": "7 — Ascensão",
        "kind": "sub",
        "name": "The Crouching Dragon's Trial",
        "level": 100,
        "trophies": [],
        "note": "",
    },
]

# A base (não é batalha): entregas, forja e reforços.
HUB_ENTRY = {
    "part": "Base",
    "kind": "base",
    "name": "Vila Oculta do Monte Tianzhushan",
    "level": 0,
    "trophies": [
        "Ascension",
    ],
    "note": "Não é batalha: é a base. Aqui você entrega as tábuas ao aldeão (cabana em frente ao silo de palha) e as Cascas ao Eremita (torre mais alta), melhora equipamento na forja e chama reforços na bandeira.",
}

# Os 75 coletáveis, cada um com a batalha, a descrição e a foto.
COLLECTIBLES = [
    {
        "kind": "Tábua",
        "name": "Yellow Turban Bandit’s Note – Part 1",
        "mission": "The Village of Calamity",
        "where": "Ao lado da primeira Bandeira de Batalha.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-1-768x432.jpg",
    },
    {
        "kind": "Tábua",
        "name": "Great Sage Mentor’s Note",
        "mission": "The Demon Fort of the Yellow Heaven",
        "where": "No fim do nível, subindo a escada atrás da pira: numa saliência do lado direito.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-11-768x432.jpg",
    },
    {
        "kind": "Tábua",
        "name": "Despairing Taoist’s Note",
        "mission": "In Search of the Immortal Wizard",
        "where": "Depois da 3ª Bandeira de Batalha, siga pelo bambuzal e ande pelo primeiro galho que vir. Pule o galho à sua frente e escale as saliências até chegar na área da tábua.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-16-768x432.jpg",
    },
    {
        "kind": "Tábua",
        "name": "Prisoner’s Last Words",
        "mission": "Fall of the Corrupted Eunuch",
        "where": "Fique de frente para a Bandeira 2, no fundo da prisão onde a água brilha roxa, como se fosse voltar ao início da área, e vá pela esquerda. Siga pelas celas até poder entrar numa com um buraco na parede. Pule esse muro, mate o Huoshu e pegue a tábua.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-21-768x432.jpg",
    },
    {
        "kind": "Tábua",
        "name": "Magnate’s Note",
        "mission": "Fall of the Corrupted Eunuch",
        "where": "Depois do chefe Baishe, siga normalmente até a biblioteca de pergaminhos com uma Bandeira de Batalha. Da bandeira, suba a escada até achar uma estante baixa que dá para pular, levando a uma sala com escada e um buraco no chão. Nessa mesma sala, atrás de caixotes destrutíveis.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-23-768x432.jpg",
    },
    {
        "kind": "Tábua",
        "name": "Sun Jian Soldier’s Letter",
        "mission": "The Battle of Hulaoguan Pass",
        "where": "Você vai precisar limpar um acampamento para descorromper uma bandeira guardada por um soldado grande de machado. Assim que entrar pelo portão principal, olhe dentro da primeira tenda à esquerda.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-28-768x432.jpg",
    },
    {
        "kind": "Tábua",
        "name": "Coalition General’s Diary",
        "mission": "The Battle of Hulaoguan Pass",
        "where": "No meio do campo de batalha, num cadáver — onde você enfrenta o mini-chefe para poder erguer a Bandeira de Batalha em frente ao portão principal.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-31-768x432.jpg",
    },
    {
        "kind": "Tábua",
        "name": "Luoyang Townswoman’s Last Words",
        "mission": "Centuries of Glory Burned Away",
        "where": "À esquerda da 2ª Bandeira de Batalha, perto de onde um Honshu embosca.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-33-768x432.jpg",
    },
    {
        "kind": "Tábua",
        "name": "Colorfully Shining Well Writings",
        "mission": "Centuries of Glory Burned Away",
        "where": "No pátio onde você descorrompe uma bandeira guardada por um Demônio Cadáver, perto da ponte do laguinho.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-36-768x432.jpg",
    },
    {
        "kind": "Tábua",
        "name": "Civil Officer’s Last Words",
        "mission": "Centuries of Glory Burned Away",
        "where": "À esquerda da bandeira final, bem no fundo, há uma Bandeira de Marcação. De frente para ela, suba no telhado à sua esquerda e desça por dentro. Está num canto.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-40-768x432.jpg",
    },
    {
        "kind": "Tábua",
        "name": "Brocade Sail Pirate’s Scribblings",
        "mission": "Darkness Over the Hanshui River",
        "where": "Bem depois no nível, ao voltar para terra firme, derrote o Shuigui que anda de um lado para o outro numa poça. Atrás dele há um píer que leva a uma saliência pintada de branco guardada por um Oficial Demonizado e um Feiticeiro. Mate os dois, suba no barco, desça para o convés inferior e olhe no fundo.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-43-768x432.jpg",
    },
    {
        "kind": "Tábua",
        "name": "Xingyang Townswoman’s Diary",
        "mission": "Darkness Over the Hanshui River",
        "where": "Volte à Bandeira de Batalha e vá para a direita. Logo depois da metade quebrada da ponte barricada, entre na casa à esquerda.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-48-768x432.jpg",
    },
    {
        "kind": "Tábua",
        "name": "Meiwu Fort Guard’s Note",
        "mission": "Tyrant's Final Banquet",
        "where": "Depois da Bandeira 2, siga pelos telhados. Cuidado com o Ninja que embosca no pé da escada. Continue pelo mesmo conjunto de telhados e vá até o canto.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-49-768x432.jpg",
    },
    {
        "kind": "Tábua",
        "name": "Meiwu Fort Jailer’s Note",
        "mission": "Tyrant's Final Banquet",
        "where": "Da bandeira na caverna, desça e derrote a patrulha do Oficial Demonizado. Logo depois dele você chega a uma bifurcação: um caminho sobe e outro leva a uma arena grande. Suba — cuidado com o Oficial Demonizado escondido na curva — e pegue no armário.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-51-768x432.jpg",
    },
    {
        "kind": "Tábua",
        "name": "Entertainer’s Diary",
        "mission": "Tyrant's Final Banquet",
        "where": "Da bandeira no jardim de bambu, escale a cerca que fica em frente à ponte.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-54-768x432.jpg",
    },
    {
        "kind": "Tábua",
        "name": "Entertainer’s Scribblings – Part 1",
        "mission": "Fate of the Entertainer",
        "where": "Subindo a escada no jardim de bambu.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-59-768x432.jpg",
    },
    {
        "kind": "Tábua",
        "name": "Entertainer’s Scribblings – Part 2",
        "mission": "Fate of the Entertainer",
        "where": "Da Bandeira de Batalha 3, você a encontra no caminho de descida até o chefe.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-61-768x432.jpg",
    },
    {
        "kind": "Tábua",
        "name": "Indulgent Military Advisor’s Diary",
        "mission": "The Uninhibited Heart",
        "where": "Ao lado da Bandeira de Batalha 2.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-68-768x432.jpg",
    },
    {
        "kind": "Tábua",
        "name": "Cao Cao Soldier’s Note",
        "mission": "Behold the Glaive of Righteousness",
        "where": "Bem depois no nível você chega a uma área de névoa. Siga o caminho principal até um Changgui, derrote-o, suba a escada longa que estava atrás dele e cruze a ponte. No fim da ponte, vá à esquerda e chute a plataforma de atalho. Suba a saliência branca e vá à esquerda.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-80-768x432.jpg",
    },
    {
        "kind": "Tábua",
        "name": "Yan Liang’s Note",
        "mission": "Behold the Glaive of Righteousness",
        "where": "Pouco antes do chefe do meio do nível, numa área corrompida com um Feiticeiro lançando magias de uma plataforma acima. Suba até essa plataforma.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-84-768x432.jpg",
    },
    {
        "kind": "Tábua",
        "name": "Tomb Robber’s Letter",
        "mission": "Behold the Glaive of Righteousness",
        "where": "Na área subterrânea, numa sala com um cristal vermelho na entrada.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-85-768x432.jpg",
    },
    {
        "kind": "Tábua",
        "name": "Disheartened Yuan Soldier’s Note",
        "mission": "Decisive Battle of Guandu",
        "where": "Da Bandeira de Batalha 1, desça — ela está no seu caminho.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-94-768x432.jpg",
    },
    {
        "kind": "Tábua",
        "name": "Yuan Zhao Assassin’s Note",
        "mission": "Decisive Battle of Guandu",
        "where": "Depois de erguer a segunda bandeira, suba pelos galhos cristalizados até uma área com um Changgui vagando e um Oficial Demonizado defendendo. Derrote os dois e passe de onde estava o Oficial até uma casa.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-95-768x432.jpg",
    },
    {
        "kind": "Tábua",
        "name": "Cao Cao Army Prisoner’s Note",
        "mission": "Decisive Battle of Guandu",
        "where": "Depois das estátuas, suba pelo galho cristalizado até um acampamento. Vá até o ponto mais alto do acampamento para achar outro galho cristalizado que leva até ela.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-99-768x432.jpg",
    },
    {
        "kind": "Tábua",
        "name": "Blindfolded Boy’s Note – Pt. 1",
        "mission": "The Crouching Dragon Roars",
        "where": "Logo no início da missão, na casa atrás de você.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-105-768x432.jpg",
    },
    {
        "kind": "Tábua",
        "name": "Blindfolded Boy’s Note – Pt. 2",
        "mission": "The Crouching Dragon Roars",
        "where": "Na mesma casa da tábua anterior.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-106-768x432.jpg",
    },
    {
        "kind": "Tábua",
        "name": "Frightened Merchant’s Note",
        "mission": "The Crouching Dragon Roars",
        "where": "À vista, enquanto você atravessa a vila.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-107-768x432.jpg",
    },
    {
        "kind": "Tábua",
        "name": "Villager’s Note",
        "mission": "The Crouching Dragon Roars",
        "where": "Do local da tábua anterior, suba a escada até uma bifurcação com escadas subindo e uma série de plataformas à direita. Vá todo à direita, passando da última plataforma.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-108-768x432.jpg",
    },
    {
        "kind": "Tábua",
        "name": "Yellow Turban Bandit’s Note – Pt. 2",
        "mission": "The Crouching Dragon Roars",
        "where": "Continue subindo a escada.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-109-768x432.jpg",
    },
    {
        "kind": "Tábua",
        "name": "Pining Woman’s Note",
        "mission": "Vila Oculta do Monte Tianzhushan",
        "where": "Atrás de uma casa, à esquerda da Bandeira de Batalha.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-111-768x432.jpg",
    },
    {
        "kind": "Tábua",
        "name": "Golden-Cicada-Obsessed Hermit’s Scribblings",
        "mission": "Vila Oculta do Monte Tianzhushan",
        "where": "Aparece depois que você entrega as 20 Cascas de Cigarra ao Eremita. Ele a derruba no mesmo telhado em que está. Se não cair, recarregue a área pela Bandeira de Batalha.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-113-768x432.jpg",
    },
    {
        "kind": "Shitieshou",
        "name": "Shitieshou",
        "mission": "The Valley of Crying Wraiths",
        "where": "Bem depois na missão: após subir uma escada e erguer uma Bandeira de Batalha, desça a colina — está à sua direita.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-5-768x432.jpg",
    },
    {
        "kind": "Shitieshou",
        "name": "Shitieshou",
        "mission": "The Demon Fort of the Yellow Heaven",
        "where": "Dentro do prédio de canto cheio de potes e caixotes, na vila.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-7-768x432.jpg",
    },
    {
        "kind": "Shitieshou",
        "name": "Shitieshou",
        "mission": "The Flying Swallow of Heishan",
        "where": "Da Bandeira de Batalha 1, siga pelas muralhas até o portão grande no fim. Antes de entrar na área do portão, olhe à direita dele, onde estão as estruturas de madeira.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-12-768x432.jpg",
    },
    {
        "kind": "Shitieshou",
        "name": "Shitieshou",
        "mission": "In Search of the Immortal Wizard",
        "where": "Ao lado da Bandeira de Batalha que fica depois do lago com o Shuigui.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-14-768x432.jpg",
    },
    {
        "kind": "Shitieshou",
        "name": "Shitieshou",
        "mission": "Shadow of the Sacred Mountain",
        "where": "Depois de erguer a bandeira que estava guardada por um Changgui, desça a escada — está num nicho de madeira pequeno à sua esquerda.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-19-768x432.jpg",
    },
    {
        "kind": "Shitieshou",
        "name": "Shitieshou",
        "mission": "Fall of the Corrupted Eunuch",
        "where": "Fique de frente para a bandeira final e a entrada do templo. Vire-se e passe da ponte até outra saliência pintada de branco que dá para escalar. Siga pelo telhado.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-26-768x432.jpg",
    },
    {
        "kind": "Shitieshou",
        "name": "Shitieshou",
        "mission": "Escape from the Capital",
        "where": "Da Bandeira de Batalha 2, entre na biblioteca de pergaminhos — está na parte de cima.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-27-768x432.jpg",
    },
    {
        "kind": "Shitieshou",
        "name": "Shitieshou",
        "mission": "The Battle of Hulaoguan Pass",
        "where": "Da bandeira no meio do campo de batalha, suba pela muralha da esquerda. No topo, vá à direita: está num prédio em frente ao Zhuyan.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-32-768x432.jpg",
    },
    {
        "kind": "Shitieshou",
        "name": "Shitieshou",
        "mission": "Centuries of Glory Burned Away",
        "where": "Num beco sem saída, em frente ao local da Casca de Cigarra Dourada.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-35-768x432.jpg",
    },
    {
        "kind": "Shitieshou",
        "name": "Shitieshou",
        "mission": "The Lost Sacred Artifact",
        "where": "Em certo ponto você cai na água. Siga por ela para encontrá-lo.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-41-768x432.jpg",
    },
    {
        "kind": "Shitieshou",
        "name": "Shitieshou",
        "mission": "Darkness Over the Hanshui River",
        "where": "Volte e passe do portão guardado por dois Fanáticos. Descorrompa a bandeira depois do portão e olhe nos prédios em frente a ela.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-45-768x432.jpg",
    },
    {
        "kind": "Shitieshou",
        "name": "Shitieshou",
        "mission": "Tyrant's Final Banquet",
        "where": "Nas cavernas você chega a uma sala guardada por um Zhupolong. Está bem onde ele está — difícil de errar.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-52-768x432.jpg",
    },
    {
        "kind": "Shitieshou",
        "name": "Shitieshou",
        "mission": "Fate of the Entertainer",
        "where": "Da Bandeira de Batalha 2, no jardim de bambu, contorne pela esquerda passando da estátua.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-58-768x432.jpg",
    },
    {
        "kind": "Shitieshou",
        "name": "Shitieshou",
        "mission": "War's Flames Blaze Fiercely",
        "where": "Na metade da missão você mata um lanceiro que controla a corrupção de uma bandeira. Passe dela e desvie para a esquerda assim que puder: num beco à esquerda há um soldado guardando.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-62-768x432.jpg",
    },
    {
        "kind": "Shitieshou",
        "name": "Shitieshou",
        "mission": "The Uninhibited Heart",
        "where": "Você chega a uma sala com um Feiticeiro que invoca raios. Use os pilares da sala para alcançar um nicho escondido com uma escada longa. No topo dela está o Shitieshou.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-70-768x432.jpg",
    },
    {
        "kind": "Shitieshou",
        "name": "Shitieshou",
        "mission": "The Way of the Warrior",
        "where": "Você chega a uma vila. Cruze a ponte e erga a Bandeira de Batalha. Diagonalmente em frente a ela, numa saliência pequena.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-73-768x432.jpg",
    },
    {
        "kind": "Shitieshou",
        "name": "Shitieshou",
        "mission": "Lu Bu, Mightiest Among Men",
        "where": "Mais adiante você entra numa sala redonda com uma estátua grande no meio. Suba até o topo e encontrará um soldado de machado. Em frente ao posto dele, numa plataforma nos fundos da estátua.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-75-768x432.jpg",
    },
    {
        "kind": "Shitieshou",
        "name": "Shitieshou",
        "mission": "Behold the Glaive of Righteousness",
        "where": "Na área de névoa: derrote o Changgui, suba a escada longa atrás dele e cruze a ponte. No fim da ponte vá à esquerda e chute a plataforma de atalho. Suba a saliência branca, vá à esquerda, suba os andaimes de madeira e vá até o telhado; então caia dentro (não onde está o Oficial Demonizado, mas logo abaixo do telhado). Lá dentro, use as plataformas quebradas.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-81-768x432.jpg",
    },
    {
        "kind": "Shitieshou",
        "name": "Shitieshou",
        "mission": "The Assault on Wuchao",
        "where": "Antes de uma Bandeira de Batalha, no mesmo corredor em que você luta contra um Leishi.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-90-768x432.jpg",
    },
    {
        "kind": "Shitieshou",
        "name": "Shitieshou",
        "mission": "Let's Make Our Armor Shine!",
        "where": "Da segunda bandeira, suba a escada perto para chegar ao topo do barco e siga pelo píer do outro lado. Derrote o soldado e solte a balsa. Siga pelo píer até subir uma escada, contorne até uma Bandeira de Marcação e vá até o topo desse barco.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-93-768x432.jpg",
    },
    {
        "kind": "Shitieshou",
        "name": "Shitieshou",
        "mission": "Decisive Battle of Guandu",
        "where": "Depois da última Bandeira de Batalha, já passado o primeiro chefe, desça para a área abaixo dela.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-102-768x432.jpg",
    },
    {
        "kind": "Shitieshou",
        "name": "Shitieshou",
        "mission": "Heirloom Seal of the Realm",
        "where": "Do início da missão, abra o portão e vá à esquerda. Siga pela rua até poder lutar com um Feiticeiro. Suba a plataforma perto dele para achar uma abertura, passe por ela e vá até o extremo do outro lado.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-104-768x432.jpg",
    },
    {
        "kind": "Shitieshou",
        "name": "Shitieshou",
        "mission": "Let's Make Our Halberds Shine!",
        "where": "Você chega a uma vila. Vá até o fim dela, onde três cães o guardam.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-110-768x432.jpg",
    },
    {
        "kind": "Casca",
        "name": "Casca",
        "mission": "Two Chivalrous Heroes",
        "where": "Depois do chefe Zhuyan, na metade do nível, suba as falésias até poder entrar num prédio. Saia do prédio e vire à direita na hora para achar uma plataforma que leva ao telhado. Siga pelo telhado, reto na bifurcação e à esquerda na primeira oportunidade.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-3-768x432.jpg",
    },
    {
        "kind": "Casca",
        "name": "Casca",
        "mission": "The Valley of Crying Wraiths",
        "where": "Depois da bandeira perto do Changgui, suba a falésia onde está um Feiticeiro. Cruze a ponte atrás e caia pelo buraco da segunda ponte.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-valley-of-crying-wraiths-golden-cicada-shell-768x432.jpg",
    },
    {
        "kind": "Casca",
        "name": "Casca",
        "mission": "The Demon Fort of the Yellow Heaven",
        "where": "Num telhado da vila, perto da escada de atalho.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-9-768x432.jpg",
    },
    {
        "kind": "Casca",
        "name": "Casca",
        "mission": "In Search of the Immortal Wizard",
        "where": "Ao entrar na caverna de corrupção vermelha, ande pelo primeiro galho que vir.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-15-768x432.jpg",
    },
    {
        "kind": "Casca",
        "name": "Casca",
        "mission": "Fall of the Corrupted Eunuch",
        "where": "Um pouco depois do início você chega à parte iluminada de uma ponte. Dali, desça pela escada, derrote os dois Huoshu e entre na cela do canto.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-20-768x432.jpg",
    },
    {
        "kind": "Casca",
        "name": "Casca",
        "mission": "Fall of the Corrupted Eunuch",
        "where": "No telhado acima da Bandeira de Batalha, no pátio dos laguinhos.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-25-768x432.jpg",
    },
    {
        "kind": "Casca",
        "name": "Casca",
        "mission": "The Battle of Hulaoguan Pass",
        "where": "Da bandeira no acampamento onde estava o soldado grande de machado, vá à direita pelo caminho lateral. Você chega ao campo de batalha com um Changgui empoleirado numa saliência à esquerda. Desça para o abismo — está no fim.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-30-768x432.jpg",
    },
    {
        "kind": "Casca",
        "name": "Casca",
        "mission": "Centuries of Glory Burned Away",
        "where": "Da segunda bandeira, vá à esquerda até uma rua com um soldado em patrulha e um arqueiro. Ao ver o soldado, vá à esquerda de novo e passe do fogo.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-34-768x432.jpg",
    },
    {
        "kind": "Casca",
        "name": "Casca",
        "mission": "Centuries of Glory Burned Away",
        "where": "Mais adiante você precisa cair por um buraco na parede até uma Bandeira de Marcação numa plataforma pequena na água. Da plataforma, de frente para o fim do canal, desça à esquerda até um nicho pequeno.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-38-768x432.jpg",
    },
    {
        "kind": "Casca",
        "name": "Casca",
        "mission": "Darkness Over the Hanshui River",
        "where": "Do início da missão, vá à direita, derrote o Shuigui e desça do topo do naufrágio de madeira no fim, caindo numa plataforma.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-42-768x432.jpg",
    },
    {
        "kind": "Casca",
        "name": "Casca",
        "mission": "Tyrant's Final Banquet",
        "where": "Depois de ser invadido, siga para a segunda parte do forte e use os telhados: está num telhadinho acima da entrada.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-50-768x432.jpg",
    },
    {
        "kind": "Casca",
        "name": "Casca",
        "mission": "Tyrant's Final Banquet",
        "where": "Depois de derrotar o mini-chefe Fengxi e erguer a bandeira, você chega a uma área guardada por um Changgui. Suba até o ponto mais alto do telhado.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-57-768x432.jpg",
    },
    {
        "kind": "Casca",
        "name": "Casca",
        "mission": "War's Flames Blaze Fiercely",
        "where": "Logo depois de liberar a corrupção de uma bandeira controlada por um lanceiro, siga o caminho e, na bifurcação, vá à direita e à direita de novo: um soldado de lança protege um baú. Mate-o e abra.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-64-768x432.jpg",
    },
    {
        "kind": "Casca",
        "name": "Casca",
        "mission": "War's Flames Blaze Fiercely",
        "where": "Nos esgotos você chega a uma sala com dois soldados de terracota sobre uma plataforma guardando um baú. A casca está dentro dele.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-65-768x432.jpg",
    },
    {
        "kind": "Casca",
        "name": "Casca",
        "mission": "The Way of the Warrior",
        "where": "Da Bandeira de Batalha 1, siga até um galho quebrado inclinado. Dali, desça à esquerda e atravesse o riacho de lama até uma área lateral defendida por um Zhupolong. Derrote-o e pegue a casca junto à árvore.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-72-768x432.jpg",
    },
    {
        "kind": "Casca",
        "name": "Casca",
        "mission": "Lu Bu, Mightiest Among Men",
        "where": "Ao chegar no topo do muro que dá vista para o forte de madeira, no fim da missão, desça e vá até a escadaria. Suba e vá à esquerda: está atrás de uma estrutura de madeira.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-78-768x432.jpg",
    },
    {
        "kind": "Casca",
        "name": "Casca",
        "mission": "Behold the Glaive of Righteousness",
        "where": "Na área de névoa: derrote o Changgui, suba a escada longa atrás dele e cruze a ponte. No fim da ponte vá à DIREITA até avistar um Suanyu. Perto da rota de patrulha dele há uma torre pequena que dá para escalar; a casca está no galho.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-83-768x432.jpg",
    },
    {
        "kind": "Casca",
        "name": "Casca",
        "mission": "Behold the Glaive of Righteousness",
        "where": "Na área subterrânea você chega a uma sala com dois soldados de terracota grandes de espada guardando uma porta. Ignore-os e escale as saliências. No topo há um buraco no chão com uma escada que leva a um atalho de volta à bandeira. Ative o atalho, volte e mate o Houshu perto do cristal vermelho. A casca está atrás do cristal.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-87-768x432.jpg",
    },
    {
        "kind": "Casca",
        "name": "Casca",
        "mission": "Decisive Battle of Guandu",
        "where": "Ao chegar nas estátuas, passe atrás da segunda à direita para alcançar uma saliência escondida.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-97-768x432.jpg",
    },
    {
        "kind": "Casca",
        "name": "Casca",
        "mission": "Decisive Battle of Guandu",
        "where": "Depois da última bandeira, já passado o primeiro chefe, desça para a área abaixo — atrás de um Shitieshou.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-103-768x432.jpg",
    },
    {
        "kind": "Casca",
        "name": "Casca",
        "mission": "Vila Oculta do Monte Tianzhushan",
        "where": "Na base da torre mais alta da vila.",
        "image": "https://www.powerpyx.com/wp-content/uploads/wo-long-fallen-dynasty-collectible-112-768x432.jpg",
    },
]

# Fecho: o que sobra para depois da história.
CLOSE = [
    {
        "name": "Entregar as 20 Cascas de Cigarra ao Eremita",
        "where": "Torre mais alta da base",
        "why": "Ascension. Existem 21 no jogo, então você tem uma de folga. FAÇA BACKUP DO SAVE antes da última entrega: há relatos do troféu não estourar.",
        "icon": "Ascension",
    },
    {
        "name": "Entregar as 31 tábuas ao aldeão",
        "where": "Cabana em frente ao silo, na base",
        "why": "Well-read, o troféu mais raro do jogo. Uma das 31 só APARECE depois de entregar as cascas — então faça na ordem: cascas primeiro, tábuas depois.",
        "icon": "Well-read",
    },
    {
        "name": "Aprender os 70 feitiços",
        "where": "Qualquer Bandeira de Batalha",
        "why": "Wizardry Master. Bandeira → Feitiços → Aprender, 14 por fase. Precisa da missão Wizardry Spell Mastery feita e de Pontos de Feitiço — por volta do nível 80 você tem o bastante.",
        "icon": "Wizardry Master",
    },
    {
        "name": "Chamar os 17 companheiros",
        "where": "The Village of Calamity",
        "why": "Great Gatherings. Na bandeira da base, escolha a missão tutorial na dificuldade Dragão Ascendente, chame um companheiro, comece e saia. Não precisa terminar.",
        "icon": "Great Gatherings",
    },
    {
        "name": "Subir um Juramento até o nível 10",
        "where": "Qualquer Bandeira de Batalha",
        "why": "Merit Beyond Measure. Se você levou reforço em toda missão, alguém já está perto. Taças de Cordialidade aceleram. No nível 10, resgate a bênção numa bandeira.",
        "icon": "Merit Beyond Measure",
    },
    {
        "name": "Arma +9 e armadura +9",
        "where": "Forja da base",
        "why": "Keen-edged e Adamantine. Vale a arma que você já usa e a peça de armadura mais barata.",
        "icon": "Keen-edged",
    },
    {
        "name": "Pote de Cura do Dragão no máximo e conjunto 4 estrelas",
        "where": "Base / inventário",
        "why": "Pots and Potions e Fantastic Form. O conjunto pede arma corpo a corpo, arma à distância, 1 acessório e 4 peças de armadura, todos 4 estrelas.",
        "icon": "Fantastic Form",
    },
    {
        "name": "Conferir bandeiras e coletáveis pendentes",
        "where": "Seleção de missão",
        "why": "Rede de segurança do Fly It High: a tela de seleção mostra o total de bandeiras erguidas por batalha. Refaça as que não estiverem completas.",
        "icon": "Fly It High",
    },
]

# 02 — Os 51 troféus do jogo base.
TROPHIES = [
    {
        "id": "plat",
        "name": "Wo Long",
        "tier": "platina",
        "requirement": "Obtenha todos os outros 50 troféus.",
        "shortcut": "Nenhum é perdível: toda missão pode ser refeita à vontade.",
        "image": "",
    },
    {
        "id": "t02",
        "name": "Open Eyes",
        "tier": "ouro",
        "requirement": "Ouça a decisão do Menino Vendado.",
        "shortcut": "Sai ao terminar a missão final, The Crouching Dragon Roars.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/ef7be662f29f55fe7b582e9ec29eba572220aacd.jpg",
    },
    {
        "id": "t03",
        "name": "Hunting the Great Deer",
        "tier": "ouro",
        "requirement": "Domine todas as batalhas principais e secundárias.",
        "shortcut": "As 46 batalhas. A aba Batalhas é o checklist.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/4d7b313381837ebfc0f19c2b5fb2dfe20a6ae6f9.jpg",
    },
    {
        "id": "t04",
        "name": "Annihilator of Evil",
        "tier": "prata",
        "requirement": "Derrote Yu Ji.",
        "shortcut": "Chefe final de The Crouching Dragon Roars.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/44f970d3bb7ed1b71a3aca05116d6142682e4a04.jpg",
    },
    {
        "id": "t05",
        "name": "Adamantine",
        "tier": "prata",
        "requirement": "Melhore uma armadura até a capacidade máxima.",
        "shortcut": "+9 na forja da base. Escolha a peça mais barata.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/f9d40ae315063b26ef1e5765b00a39f8acd46765.jpg",
    },
    {
        "id": "t06",
        "name": "Keen-edged",
        "tier": "prata",
        "requirement": "Melhore uma arma até a capacidade máxima.",
        "shortcut": "+9 na forja da base, na arma que você já usa.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/d2bbfdedca3d1abb5033f40d9c15b6d1d40c0f0b.jpg",
    },
    {
        "id": "t07",
        "name": "Ascension",
        "tier": "prata",
        "requirement": "Dê a quantidade máxima de Cascas de Cigarra Dourada.",
        "shortcut": "20 das 21 ao Eremita, na torre mais alta da base.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/ccc33cdd80528faab55cf68d0196325123a6535d.jpg",
    },
    {
        "id": "t08",
        "name": "Battle-hardened",
        "tier": "prata",
        "requirement": "Domine 15 batalhas secundárias.",
        "shortcut": "Sai sozinho: são 30 e você precisa de todas para o Hunting the Great Deer.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/22801402bb34303611337706ca09ea3f89fccaf3.jpg",
    },
    {
        "id": "t09",
        "name": "Pots and Potions",
        "tier": "prata",
        "requirement": "Melhore o Pote de Cura do Dragão ao máximo.",
        "shortcut": "Use os Cristais e Essências de Veia de Dragão que caem nas missões.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/e9615857ea568381580e71e2a0a5aaa92fedb999.jpg",
    },
    {
        "id": "t10",
        "name": "Fly It High",
        "tier": "prata",
        "requirement": "Erga todas as Bandeiras de Batalha.",
        "shortcut": "145 bandeiras somando as 46 batalhas. Se você erguer tudo na primeira passagem, sai sozinho.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/b24ea78d9642d16bb52d42531e1a35b7eca2ec22.jpg",
    },
    {
        "id": "t11",
        "name": "How Precious!",
        "tier": "prata",
        "requirement": "Alimente todos os Shitieshou.",
        "shortcut": "Os 23 pandas. Qualquer peça de equipamento serve de comida.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/736c00a8db372f39b2993da22d195ca68ed4b111.jpg",
    },
    {
        "id": "t12",
        "name": "Well-read",
        "tier": "prata",
        "requirement": "Colete todas as tábuas.",
        "shortcut": "As 31 tábuas — o troféu mais raro do jogo.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/ecc38616d3ea942720a1a7bdcdee8888d4b38d08.jpg",
    },
    {
        "id": "t13",
        "name": "Wizardry Master",
        "tier": "prata",
        "requirement": "Aprenda todos os feitiços.",
        "shortcut": "Os 70 (14 por fase). Exige a batalha Wizardry Spell Mastery feita.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/3df3d4b302c94f49a2788deadbee2acfa8c2e7c9.jpg",
    },
    {
        "id": "t14",
        "name": "Vow of the Stalwart",
        "tier": "bronze",
        "requirement": "Juramento com Zhao Yun.",
        "shortcut": "Automático ao terminar Two Chivalrous Heroes.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/c43448a44aa1f3cb5984d29acbfac5b76cd33219.jpg",
    },
    {
        "id": "t15",
        "name": "Will of the Loyal",
        "tier": "bronze",
        "requirement": "Juramento com Guan Yu e Zhang Fei.",
        "shortcut": "Automático ao terminar The Valley of Crying Wraiths.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/239975b93f44ba5d2fb16bdd3f78e7bf7b92226f.jpg",
    },
    {
        "id": "t16",
        "name": "Ambition of the Tiger",
        "tier": "bronze",
        "requirement": "Juramento com Sun Jian.",
        "shortcut": "Automático ao terminar The Demon Fort of the Yellow Heaven.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/38b23e9c3f39a7aa6e0eaf6e5d1aaf446b4f615d.jpg",
    },
    {
        "id": "t17",
        "name": "Guardian of Peace",
        "tier": "bronze",
        "requirement": "Juramento com Zuo Ci.",
        "shortcut": "Automático ao terminar In Search of the Immortal Wizard.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/6953d1d1f4dfe037d1b30487a6ed23b016260e2e.jpg",
    },
    {
        "id": "t18",
        "name": "Awakening of the Unscrupulous Hero",
        "tier": "bronze",
        "requirement": "Juramento com Cao Cao.",
        "shortcut": "Ao terminar Fall of the Corrupted Eunuch. Jogue essa missão SOZINHO: há relatos de bug em co-op.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/e68c6278a6124e0f201cc39957970c14a5a19b5a.jpg",
    },
    {
        "id": "t19",
        "name": "Guidance of the Constellations",
        "tier": "bronze",
        "requirement": "Juramento com Lady Zhen.",
        "shortcut": "Automático ao terminar Centuries of Glory Burned Away.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/30cf073dbacdcd728d16d7b411d8ed93c8f710e8.jpg",
    },
    {
        "id": "t20",
        "name": "Succession",
        "tier": "bronze",
        "requirement": "Juramentos com Sun Ce e Sun Quan.",
        "shortcut": "Automático ao terminar Darkness Over the Hanshui River.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/178e99e459290feba46fdb0a7167ac0edaccf422.jpg",
    },
    {
        "id": "t21",
        "name": "Familial Ties",
        "tier": "bronze",
        "requirement": "Juramento com Hong Jing.",
        "shortcut": "Automático ao terminar Tyrant's Final Banquet.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/4ce94efb2bbba633fd24cfa618b6d4e261395435.jpg",
    },
    {
        "id": "t22",
        "name": "The Steadfast Duo",
        "tier": "bronze",
        "requirement": "Juramentos com Xiahou Dun e Xiahou Yuan.",
        "shortcut": "Automático ao terminar War's Flames Blaze Fiercely.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/73aeebc67663501ecdf959d6b93d9fc058dd42f6.jpg",
    },
    {
        "id": "t23",
        "name": "Fearless Warrior",
        "tier": "bronze",
        "requirement": "Juramento com Zhang Liao.",
        "shortcut": "Automático ao terminar The Way of the Warrior.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/086ad794c1496e9ba54684e9f619cbe588803784.jpg",
    },
    {
        "id": "t24",
        "name": "Entrusted Legacy",
        "tier": "bronze",
        "requirement": "Juramento com Lu Bu.",
        "shortcut": "Automático ao terminar Lu Bu, Mightiest Among Men.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/0d94c48593b1bb35d7efc096e4a807463e61f8d1.jpg",
    },
    {
        "id": "t25",
        "name": "Aspiration and Amity",
        "tier": "bronze",
        "requirement": "Juramento com Liu Bei.",
        "shortcut": "Automático ao terminar Behold the Glaive of Righteousness.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/1cf7e834978ceb533131dfc080ad990cc6e4b002.jpg",
    },
    {
        "id": "t26",
        "name": "Dreams of Unity",
        "tier": "bronze",
        "requirement": "Juramento com Yuan Shao.",
        "shortcut": "Automático ao terminar Decisive Battle of Guandu.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/0e8600845870238c5076922c0ae331641333739c.jpg",
    },
    {
        "id": "t27",
        "name": "Journey's Beginning",
        "tier": "bronze",
        "requirement": "Desperte do sono da morte.",
        "shortcut": "Automático no começo do jogo.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/eceaca0f379d8821934108b90b34d93168cf0fc9.jpg",
    },
    {
        "id": "t28",
        "name": "Staunching Heresy",
        "tier": "bronze",
        "requirement": "Derrote todos os Feiticeiros que fazem o ritual.",
        "shortcut": "Em The Valley of Crying Wraiths: limpe os feiticeiros antes de ir ao chefe.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/5f68232e65afdb615ed8a696f6a93d8263458c72.jpg",
    },
    {
        "id": "t29",
        "name": "Dogged Justice",
        "tier": "bronze",
        "requirement": "Salve os eremitas capturados.",
        "shortcut": "Em Fall of the Corrupted Eunuch, antes de terminar a missão.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/2099dc7fe7e3b1c5b674656bbee07db4a825037c.jpg",
    },
    {
        "id": "t30",
        "name": "Mightiest of Men",
        "tier": "bronze",
        "requirement": "Repila as forças de Lu Bu.",
        "shortcut": "Em The Battle of Hulaoguan Pass.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/3cc22c370bd1bd80c7fb4fa59aefcff57d16698b.jpg",
    },
    {
        "id": "t31",
        "name": "Strung Bow",
        "tier": "bronze",
        "requirement": "Derrote 5 inimigos com uma balista.",
        "shortcut": "Nas balistas da muralha em The Battle of Hulaoguan Pass.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/36316fd42aa347d4f2b2419af0f406f88fd99021.jpg",
    },
    {
        "id": "t32",
        "name": "Heroes will Rise",
        "tier": "bronze",
        "requirement": "Repila o Xielong.",
        "shortcut": "Em Centuries of Glory Burned Away.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/7f0a439a029dad65f150bc47e7b27168e14b1bc1.jpg",
    },
    {
        "id": "t33",
        "name": "At Fifteen I Joined the Army",
        "tier": "bronze",
        "requirement": "Chegue ao nível 15.",
        "shortcut": "Sai sozinho na Parte 2.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/2b9072d02e0bb2f71315c1805dc19b7f258e92a1.jpg",
    },
    {
        "id": "t34",
        "name": "Only at Eighty Did I Finally Return",
        "tier": "bronze",
        "requirement": "Chegue ao nível 80.",
        "shortcut": "Sai sozinho: as últimas batalhas pedem nível 90+.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/99f1d3cf321b61298ebe72e3ab4b019631895af7.jpg",
    },
    {
        "id": "t35",
        "name": "Best Flag Forward",
        "tier": "bronze",
        "requirement": "Erga sua primeira Bandeira de Batalha.",
        "shortcut": "Primeiros minutos.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/640b5a283e176f960c17b31fd7e535fa5803b6f3.jpg",
    },
    {
        "id": "t36",
        "name": "Wizardry Beginner",
        "tier": "bronze",
        "requirement": "Aprenda seu primeiro feitiço.",
        "shortcut": "Numa bandeira: Feitiços → Aprender.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/3b944ecdefaa62d9405280ecfb5ae1bf2b9792d9.jpg",
    },
    {
        "id": "t37",
        "name": "First Phase",
        "tier": "bronze",
        "requirement": "Interaja com as Cinco Fases pela primeira vez.",
        "shortcut": "Não basta lançar feitiços: use um que ANULE o elemento do inimigo (Metal anula Madeira, Fogo anula Metal, Água anula Fogo, Terra anula Água, Madeira anula Terra).",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/922747d2338265d5b3f2039428e694538b450bcc.jpg",
    },
    {
        "id": "t38",
        "name": "Unstoppable",
        "tier": "bronze",
        "requirement": "Chegue ao Rank de Moral 20 numa batalha.",
        "shortcut": "Fácil numa batalha antiga em que sua Fortitude já esteja alta: erga tudo e mate sem morrer.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/a7dbaa1c7e8a89d89bb28e38a912cfea1ea9a47b.jpg",
    },
    {
        "id": "t39",
        "name": "How Cute!",
        "tier": "bronze",
        "requirement": "Alimente seu primeiro Shitieshou.",
        "shortcut": "O primeiro está em The Valley of Crying Wraiths.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/b63529d255c993035fc3c4f967353f56493cc2c8.jpg",
    },
    {
        "id": "t40",
        "name": "Craftsmanship",
        "tier": "bronze",
        "requirement": "Melhore sua primeira peça de equipamento.",
        "shortcut": "Forja da base.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/0ebc63218848640d4801721f33da9b2a2132e06c.jpg",
    },
    {
        "id": "t41",
        "name": "All that Glitters",
        "tier": "bronze",
        "requirement": "Encaixe sua primeira joia na forja.",
        "shortcut": "Forja → Encaixar.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/ef23cff733b30b662755cbf950b9c9c657c0041e.jpg",
    },
    {
        "id": "t42",
        "name": "Decor Maketh the Man",
        "tier": "bronze",
        "requirement": "Decore seu primeiro item na forja.",
        "shortcut": "Forja → Decorar. Só muda a aparência.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/6b1f1a3af6cb6e906cb0a346ebe95c45e492081f.jpg",
    },
    {
        "id": "t43",
        "name": "Fantastic Form",
        "tier": "bronze",
        "requirement": "Equipe um conjunto completo de 4 estrelas.",
        "shortcut": "Arma corpo a corpo, arma à distância, 1 acessório e 4 peças de armadura, todos 4 estrelas.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/ae2af9a47c65ba3e5eb10342c2e1ce4b9bbcdc2a.jpg",
    },
    {
        "id": "t44",
        "name": "Sharp Reflexes",
        "tier": "bronze",
        "requirement": "Desvie de 10 golpes críticos.",
        "shortcut": "Os ataques vermelhos. Sai sozinho, é a mecânica central.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/72d96a140ea3efaf27dabc78f7c5947c7a5a9612.jpg",
    },
    {
        "id": "t45",
        "name": "Vulnerable Moments",
        "tier": "bronze",
        "requirement": "Acerte 50 Golpes Fatais.",
        "shortcut": "O contra-ataque depois de quebrar o Espírito do inimigo.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/165dc078699ffe8537ded23f0b28a137a635a893.jpg",
    },
    {
        "id": "t46",
        "name": "Righteous Judgment",
        "tier": "bronze",
        "requirement": "Vingue-se 10 vezes.",
        "shortcut": "Mate o inimigo marcado que te matou.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/a7d7da49b59d43d04aca5673f767225050beb136.jpg",
    },
    {
        "id": "t47",
        "name": "Eye for an Eye",
        "tier": "bronze",
        "requirement": "Repila invasores 10 vezes.",
        "shortcut": "Só invasores NPC contam — desative a invasão por jogadores nas opções.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/4f2f9f2f9b1610ac459bb89f8fe2144f3abd57cc.jpg",
    },
    {
        "id": "t48",
        "name": "Side by Side",
        "tier": "bronze",
        "requirement": "Domine 10 batalhas com um companheiro.",
        "shortcut": "Chame um reforço na bandeira antes de iniciar. Faça sempre.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/52350473647fd406fbe92f6f5d5382f55e9cb027.jpg",
    },
    {
        "id": "t49",
        "name": "Call to Arms",
        "tier": "bronze",
        "requirement": "Use 10 Selos do Tigre.",
        "shortcut": "Selos de recrutamento, usados na bandeira.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/3968a3226408e3dd5786c07a34cdb1081b17e2cb.jpg",
    },
    {
        "id": "t50",
        "name": "Great Gatherings",
        "tier": "bronze",
        "requirement": "Junte forças com todos os guerreiros.",
        "shortcut": "Chame cada um dos 17 pelo menos uma vez. Ver o Fecho na aba Batalhas.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/04bfbb5d8bc19561fa72604c9afcd17339cfec1e.jpg",
    },
    {
        "id": "t51",
        "name": "Merit Beyond Measure",
        "tier": "bronze",
        "requirement": "Receba a bênção de um irmão de juramento.",
        "shortcut": "Suba o Juramento de um companheiro até 10 e resgate numa bandeira.",
        "image": "https://shared.fastly.steamstatic.com/community_assets/images/apps/1448440/0306f61755667f0aaf78783548b2f676df5fc1e8.jpg",
    },
]

# 03 — As Cinco Fases (14 feitiços cada = 70).
PHASES = [
    {
        "name": "Madeira (Wood)",
        "spells": "14 feitiços",
        "note": "Cura e suporte. Anula a Terra.",
    },
    {
        "name": "Fogo (Fire)",
        "spells": "14 feitiços",
        "note": "Dano e queimadura. Anula o Metal.",
    },
    {
        "name": "Terra (Earth)",
        "spells": "14 feitiços",
        "note": "Defesa e controle. Anula a Água.",
    },
    {
        "name": "Metal (Metal)",
        "spells": "14 feitiços",
        "note": "Raio e perfuração. Anula a Madeira.",
    },
    {
        "name": "Água (Water)",
        "spells": "14 feitiços",
        "note": "Furtividade e gelo. Anula o Fogo.",
    },
]

# 03 — Os 17 guerreiros recrutáveis.
COMPANIONS = [
    {
        "name": "Zhao Yun",
        "when": "Two Chivalrous Heroes (Parte 2)",
    },
    {
        "name": "Guan Yu",
        "when": "The Valley of Crying Wraiths (Parte 2)",
    },
    {
        "name": "Zhang Fei",
        "when": "The Valley of Crying Wraiths (Parte 2)",
    },
    {
        "name": "Sun Jian",
        "when": "The Demon Fort of the Yellow Heaven (Parte 2)",
    },
    {
        "name": "Cao Cao",
        "when": "Fall of the Corrupted Eunuch (Parte 3)",
    },
    {
        "name": "Zhang Jiao",
        "when": "Ao longo da campanha",
    },
    {
        "name": "Xun Yu",
        "when": "Ao longo da campanha",
    },
    {
        "name": "Hong Jing",
        "when": "Tyrant's Final Banquet (Parte 4)",
    },
    {
        "name": "Sun Ce",
        "when": "Darkness Over the Hanshui River (Parte 4)",
    },
    {
        "name": "Sun Quan",
        "when": "Darkness Over the Hanshui River (Parte 4)",
    },
    {
        "name": "Han Dang",
        "when": "Missões do clã Sun (Parte 4)",
    },
    {
        "name": "Cheng Pu",
        "when": "Missões do clã Sun (Parte 4)",
    },
    {
        "name": "Huang Gai",
        "when": "Missões do clã Sun (Parte 4)",
    },
    {
        "name": "Xiahou Dun",
        "when": "War's Flames Blaze Fiercely (Parte 5)",
    },
    {
        "name": "Xiahou Yuan",
        "when": "War's Flames Blaze Fiercely (Parte 5)",
    },
    {
        "name": "Zhang Liao",
        "when": "The Way of the Warrior (Parte 5)",
    },
    {
        "name": "Liu Bei",
        "when": "Behold the Glaive of Righteousness (Parte 6)",
    },
]

# 03 — Hábitos e ajustes que evitam grind.
PREP = [
    {
        "name": "Desativar a invasão por jogadores",
        "when": "Antes da 1ª missão",
        "why": "O Eye for an Eye só conta invasores NPC. Com jogadores reais entrando no lugar deles, a contagem trava e vira grind no fim.",
    },
    {
        "name": "Jogar Fall of the Corrupted Eunuch sozinho",
        "when": "Parte 3",
        "why": "O juramento com Cao Cao tem relatos de não estourar quando a missão é feita em co-op.",
    },
    {
        "name": "Chamar um reforço antes de TODA missão",
        "when": "Sempre",
        "why": "Não custa nada, ajuda na luta, conta para Side by Side (10 batalhas) e sobe o Juramento — que é o que libera o Merit Beyond Measure.",
    },
    {
        "name": "Erguer todas as bandeiras na primeira passagem",
        "when": "Sempre",
        "why": "Bandeira de Marcação sobe a Fortitude, que é o PISO do seu Rank de Moral naquela batalha. É o que faz o jogo ficar mais fácil em vez de mais difícil — e é o Fly It High saindo de graça.",
    },
    {
        "name": "Não pular a batalha Wizardry Spell Mastery",
        "when": "Parte 3, nível 32",
        "why": "É ela que libera os feitiços de tier alto. Sem ela o Wizardry Master é impossível, e muita gente só descobre no fim da run.",
    },
]

# 04 — Fontes consultadas.
SOURCES = [
    {
        "title": "PowerPyx — Trophy Guide & Roadmap",
        "url": "https://www.powerpyx.com/wo-long-fallen-dynasty-trophy-guide-roadmap/",
        "note": "Roteiro, avisos de bug (Cao Cao em co-op, Eye for an Eye) e a lista dos 17 companheiros.",
    },
    {
        "title": "PowerPyx — Tablets, Shitieshou e Golden Cicada Shells",
        "url": "https://www.powerpyx.com/wo-long-fallen-dynasty-all-collectible-locations/",
        "note": "Origem dos 75 locais e das fotos de cada coletável deste guia.",
    },
    {
        "title": "Fextralife — Trophy & Achievement Guide",
        "url": "https://wolong.wiki.fextralife.com/Trophy+&+Achievement+Guide",
        "note": "Lista dos 51 troféus com os tiers conferidos (1 platina, 2 ouro, 10 prata, 38 bronze).",
    },
    {
        "title": "Game8 — List of Missions",
        "url": "https://game8.co/games/Wo-Long-Fallen-Dynasty/archives/406772",
        "note": "As 46 batalhas por parte, com o nível recomendado de cada uma.",
    },
    {
        "title": "Fextralife — Great Gatherings / Wizardry Master",
        "url": "https://wolong.wiki.fextralife.com/Great+Gatherings",
        "note": "Método rápido dos 17 companheiros e o pré-requisito da Wizardry Spell Mastery.",
    },
    {
        "title": "PSNProfiles — Wo Long: Fallen Dynasty",
        "url": "https://psnprofiles.com/trophies/21250-wo-long-fallen-dynasty",
        "note": "Conferência da divisão oficial dos troféus e das raridades.",
    },
]

# Rodapé do guia.
FOOTER = "Wo Long: Fallen Dynasty — Platina PT-BR • guia não oficial • progresso salvo em %APPDATA%/StreamerSidekick/platinas/wolong/"

